Feature/1882 custom reward destination
momentum-xyz/ui-client pull request #108
Opened 2022-06-24 14:05 UTC by Danchev1

2022-06-24 14:31 UTC, PAKovalev requested changes

2022-06-24 14:31 UTC, PAKovalev commented on src/scenes/widgets/pages/StakingWidget/components/templates/Nominator/Nominator.tsx
> +    let unsubscribe: any;
why any? Maybe we can declare this function

2022-06-24 14:31 UTC, PAKovalev commented on src/scenes/widgets/pages/StakingWidget/components/templates/Nominator/components/RewardValidator/RewardValidator.tsx
> +import {t} from 'i18next';
I suggest to use `useTranslation` hook in components. You can changes in fly.

2022-06-24 14:31 UTC, PAKovalev commented on src/scenes/widgets/pages/StakingWidget/components/templates/Nominator/components/RewardValidator/RewardValidator.tsx
> +interface PropsInterface extends PropsWithThemeInterface {}
No need empty interface

2022-06-24 14:31 UTC, PAKovalev commented on src/scenes/widgets/stores/StakingStore/models/PolkadotProviderStore/PolkadotProviderStore.ts
> +      customPaymentDestination: types.optional(types.string, ''),
FYI: You can use just `''` instead of `types.optional(types.string, '')`

2022-06-27 06:03 UTC, Danchev1 commented on src/scenes/widgets/pages/StakingWidget/components/templates/Nominator/components/RewardValidator/RewardValidator.tsx
> +interface PropsInterface extends PropsWithThemeInterface {}
done

2022-06-27 06:03 UTC, Danchev1 commented on src/scenes/widgets/pages/StakingWidget/components/templates/Nominator/Nominator.tsx
> +    let unsubscribe: any;
done

2022-06-27 06:05 UTC, Danchev1 commented on src/scenes/widgets/stores/StakingStore/models/PolkadotProviderStore/PolkadotProviderStore.ts
> +      customPaymentDestination: types.optional(types.string, ''),
done

2022-06-27 08:27 UTC, PAKovalev approved these changes

2022-06-27 09:31 UTC, aminbksi approved these changes

2022-06-27 09:57 UTC, merged