h5 posbus notification type with translation fix
momentum-xyz/ui-client pull request #119
Opened 2022-07-05 09:28 UTC by aminbksi

2022-07-05 10:48 UTC, Danchev1 approved these changes

2022-07-06 07:09 UTC, PAKovalev requested changes

2022-07-06 07:09 UTC, PAKovalev commented on src/context/Websocket/WebsocketService.tsx
> +      toast.info(
Use `usePosBusEvent` to show this message. Use `UnityPage`.

2022-07-06 07:10 UTC, PAKovalev approved these changes

2022-07-06 07:13 UTC, merged