Feature/#1852 grand rework dashboard page store
momentum-xyz/ui-client pull request #127
Opened 2022-07-06 14:36 UTC by aminbksi

2022-07-06 14:42 UTC, PAKovalev commented on src/core/models/Content/Content.ts
> +  .views((self) => ({}));
empty

2022-07-06 14:43 UTC, PAKovalev commented on src/core/models/Tile/Tile.ts
> +  .views((self) => ({}));
empty

2022-07-06 14:43 UTC, PAKovalev commented on src/core/models/TileList/TileList.ts
> +import {Tile, TileInterface} from '../Tile';
from 'core/models'

2022-07-06 14:44 UTC, PAKovalev commented on src/core/models/TileList/TileList.ts
> +    get tileMatrix() {
`get tileMatrix(): TileInterface[][] {`. I mean `return type`.

2022-07-06 14:45 UTC, PAKovalev commented on src/scenes/collaboration/pages/DashboardPage/DashboardPage.tsx
> +      UnityService.triggerInteractionMsg?.(
Make action under `UnityService`

2022-07-06 14:47 UTC, PAKovalev commented on src/scenes/collaboration/pages/DashboardPage/components/templates/Dashboard/components/TileItem/components/TileDetail.tsx
> +  } = useStore();
Don't use store in this component. Make props.

2022-07-06 14:48 UTC, PAKovalev commented on src/scenes/collaboration/stores/DashboardStore/DashboardStore.ts
> +      dashboardStore: types.optional(Dashboard, {})
`dashboard: types.optional(Dashboard, {})`

2022-07-06 14:50 UTC, PAKovalev commented on src/scenes/collaboration/stores/DashboardStore/models/Dashboard/Dashboard.ts
> +              (tile.permanentType === PermanentType.POSTER ||
`[PermanentType.POSTER, PermanentType.MEME, PermanentType.DESCRIPTION, PermanentType.DESCRIPTION].includes(tile.permanentType) {}` will be smaller.

2022-07-06 14:51 UTC, PAKovalev commented on src/scenes/collaboration/stores/DashboardStore/models/Dashboard/Dashboard.ts
> +        self.videoUrl = `https://www.youtube.com/embed/${youtubeVideoPath(
Make `youtubeVideoFullPath`

2022-07-06 14:51 UTC, PAKovalev commented on src/scenes/collaboration/stores/DashboardStore/models/Dashboard/Dashboard.ts
> +      setTilesWithPositions(tiles: TileInterface[][]) {
Return type

2022-07-06 14:51 UTC, PAKovalev commented on src/scenes/collaboration/stores/DashboardStore/models/Dashboard/Dashboard.ts
> +      onDragEnd({source, destination}: DropResult) {
return type

2022-07-06 14:52 UTC, PAKovalev commented on src/shared/services/i18n/locales/en-gb.ts
> +      updateSpace: 'UPDATE YOUR SPACE WITH SOME ENTICING CONTENT'
Why do you uppercase? Do it using css

2022-07-06 14:53 UTC, PAKovalev commented on src/ui-kit/molecules/TileMenu/TileMenu.styled.ts
> +export const SvgItem = styled(SvgButton)``;
Don't mix styles.

2022-07-07 07:28 UTC, PAKovalev approved these changes

2022-07-07 10:31 UTC, Danchev1 commented on src/core/utils/image.utils.ts
> +// @ts-ignore
can we remove ts-ignore the method looks generic, what is the problem?

2022-07-07 10:31 UTC, Danchev1 commented on src/core/utils/image.utils.ts
> +// @ts-ignore
can we remove ts-ignore the method looks generic, what is the problem?

2022-07-07 10:31 UTC, Danchev1 requested changes

2022-07-07 10:31 UTC, Danchev1 commented on src/core/utils/image.utils.ts
> +// @ts-ignore
can we remove ts-ignore the method looks generic, what is the problem?

2022-07-07 10:33 UTC, Danchev1 requested changes

2022-07-07 10:33 UTC, Danchev1 commented on src/scenes/collaboration/pages/DashboardPage/components/templates/Dashboard/components/TileItem/components/TileDetail.tsx
> +  const handleEdit = () => {
maybe you forgot them?

2022-07-07 15:11 UTC, merged