Feature/#2008 collaboration routes
momentum-xyz/ui-client pull request #140
Opened 2022-07-20 13:50 UTC by PAKovalev

2022-07-20 15:08 UTC, Daboo1998 requested changes

2022-07-20 15:08 UTC, Daboo1998 commented on src/api/repositories/magicRepository/magicRepository.api.endpoints.ts
> +    fetchLink: `${BASE_URL}/:key`,
It think it should be id or magicId instead of key (The same is in swagger)

2022-07-20 15:08 UTC, Daboo1998 commented on src/scenes/magic/pages/MagicPage/MagicPage.tsx
> +    magicStore.getMagicLink(key);
It think it should be id or magicId instead of key (The same is in swagger). We need to change key to id everywhere if we use that instead.

2022-07-20 15:36 UTC, PAKovalev commented on src/scenes/collaboration/Collaboration.tsx
> +const Collaboration: FC = () => {
I use FC all the time.

2022-07-21 06:45 UTC, aminbksi approved these changes

2022-07-21 07:51 UTC, Daboo1998 approved these changes

2022-07-21 07:55 UTC, merged