Feature/clean unused state props 2009
momentum-xyz/ui-client pull request #145
Opened 2022-07-27 14:29 UTC by Daboo1998

2022-07-27 14:48 UTC, PAKovalev requested changes

2022-07-27 14:48 UTC, PAKovalev commented on src/api/repositories/agoraRepository/agoraRepository.api.ts
> +export const getAgoraToken: RequestInterface<AgoraTokenRequest, AgoraTokenResponse> = (options) => {
Can we create two functions? getAgoraToken & getAgoraScreenShareToken

2022-07-27 14:48 UTC, PAKovalev commented on src/api/repositories/spaceIntegrationsRepository/spaceIntegrations.api.types.ts
> +  extends Omit<SpaceIntegrationInterface, 'spaceId'> {
Why?

2022-07-27 14:48 UTC, PAKovalev commented on src/core/models/Space/Space.ts
> +import {GetAllowedSpaceTypesResponse} from 'api/repositories/spaceTypeRepository/spaceTypeRepository.api.types';
`import {GetAllowedSpaceTypesResponse} from 'api';`

2022-07-27 14:48 UTC, PAKovalev commented on src/core/models/Space/Space.ts
> +    setup(spaceId: string, isTable = false) {
unused function

2022-07-27 14:48 UTC, PAKovalev commented on src/scenes/collaboration/Collaboration.tsx
> +  const [isModerator, , ,] = useModerator(spaceId);
Can we refactor?

2022-07-27 14:48 UTC, PAKovalev commented on src/scenes/collaboration/Collaboration.tsx
> +  useEffect(() => {
Remove. It is in UnityPage.

2022-07-27 14:48 UTC, PAKovalev commented on src/scenes/collaboration/Collaboration.tsx
> +  useEffect(() => {
Can we move to RootStore? + leaveMeeting?

2022-07-27 14:48 UTC, PAKovalev commented on src/scenes/collaboration/pages/CalendarPage/CalendarPage.tsx
> +  const handleClose = async () => {
Move to RootStore

2022-07-27 14:48 UTC, PAKovalev commented on src/scenes/collaboration/stores/RootCollaborationStore.ts
> +    joinMeetingSpace: flow(function* (spaceId: string, isTable = false) {
Move to RootStore

2022-07-27 14:48 UTC, PAKovalev commented on src/scenes/collaboration/stores/RootCollaborationStore.ts
> +      UnityService.triggerInteractionMsg?.(PosBusEventEnum.EnteredSpace, spaceId, 0, '');
Use store after moving

2022-07-27 15:01 UTC, Daboo1998 commented on src/api/repositories/spaceIntegrationsRepository/spaceIntegrations.api.types.ts
> +  extends Omit<SpaceIntegrationInterface, 'spaceId'> {
Cause the extended interface has spaceId of different type, and didn't want to redeclare other fields again. Its bacause of BE, we need to also refactor BE EP's :)

2022-07-27 15:02 UTC, Daboo1998 commented on src/scenes/collaboration/Collaboration.tsx
> +  const [isModerator, , ,] = useModerator(spaceId);
Yes, we can! :) 

unless you want it to be part of a different ticket

2022-07-27 15:07 UTC, PAKovalev commented on src/api/repositories/agoraRepository/agoraRepository.api.ts
> +export const getAgoraToken: RequestInterface<AgoraTokenRequest, AgoraTokenResponse> = (options) => {
2 will better.

2022-07-27 15:09 UTC, PAKovalev commented on src/scenes/collaboration/Collaboration.tsx
> +  const [isModerator, , ,] = useModerator(spaceId);
It is time to refactor )

2022-07-27 15:20 UTC, Daboo1998 commented on src/scenes/collaboration/Collaboration.tsx
> +  const [isModerator, , ,] = useModerator(spaceId);
Ok 👍

2022-07-27 15:22 UTC, aminbksi commented on src/component/molucules/TopBar.tsx
> +    return currentLocation.pathname.includes('/space/' + space.id + '/admin');
use Routes maybe?

2022-07-27 15:23 UTC, PAKovalev commented on src/component/molucules/TopBar.tsx
> +    return currentLocation.pathname.includes('/space/' + space.id + '/admin');
We have to remove this component.

2022-07-27 15:32 UTC, aminbksi requested changes

2022-07-27 15:32 UTC, aminbksi commented on src/component/overlays/VideoLayer.tsx
>  import {ROUTES} from '../../core/constants';
path

2022-07-28 07:20 UTC, Daboo1998 commented on src/core/models/Space/Space.ts
> +import {GetAllowedSpaceTypesResponse} from 'api/repositories/spaceTypeRepository/spaceTypeRepository.api.types';
For that I would have to add `export * from './spaceTypeRepository.api.types';` to `api/repositories/spaceTypeRepository/index.ts` and `import * from './repositories';` to `api/index.ts`. We never did that, do you want to do that?

2022-07-28 07:23 UTC, Daboo1998 commented on src/scenes/collaboration/Collaboration.tsx
> +  useEffect(() => {
I added it cause it didn't pause unity when loading from url. Are you sure its done correctly in UnityPage? Or is it a recent change?

2022-07-28 07:45 UTC, Daboo1998 commented on src/scenes/collaboration/pages/CalendarPage/CalendarPage.tsx
> +  const handleClose = async () => {
I will even remove the calls, going to ROUTES.base should trigger the useEffect return from Collaboration.tsx

2022-07-28 07:47 UTC, Daboo1998 commented on src/scenes/collaboration/stores/RootCollaborationStore.ts
> +    joinMeetingSpace: flow(function* (spaceId: string, isTable = false) {
No I will just call it from RootStore and call the unity stuff from there

2022-07-28 07:48 UTC, Daboo1998 commented on src/component/molucules/TopBar.tsx
> +    return currentLocation.pathname.includes('/space/' + space.id + '/admin');
So I will leave it for now

2022-07-28 07:49 UTC, Daboo1998 commented on src/component/overlays/VideoLayer.tsx
>  import {ROUTES} from '../../core/constants';
It wasn't't my change but I can change that

2022-07-28 09:25 UTC, PAKovalev approved these changes

2022-07-28 09:25 UTC, aminbksi approved these changes

2022-07-28 09:31 UTC, merged