Feature/remove page topbar
momentum-xyz/ui-client pull request #162
Opened 2022-08-03 14:21 UTC by aminbksi

2022-08-03 15:27 UTC, Daboo1998 requested changes

2022-08-03 15:27 UTC, Daboo1998 commented on src/modules/broadcastadmin/layout/BroadCastAdminLayout.tsx
> +        subtitle="Manage Broadcast"
translation

2022-08-04 07:13 UTC, Daboo1998 approved these changes

2022-08-04 07:27 UTC, PAKovalev approved these changes

2022-08-04 07:44 UTC, merged