Feature/#2013 user profile
momentum-xyz/ui-client pull request #186
Opened 2022-08-17 15:43 UTC by aminbksi

2022-08-17 16:32 UTC, dmitry-yudakov commented on src/scenes/widgets/pages/ProfileWidget/components/templates/UserProfileView/UserProfileView.tsx
> +                  }}
@aminbksi Perhaps it's better be in `handleSendHighFive` function like for the rest of the handlers?

2022-08-18 07:07 UTC, Daboo1998 requested changes

2022-08-18 07:07 UTC, Daboo1998 commented on src/scenes/widgets/pages/ProfileWidget/components/templates/MyProfileEdit/components/AvatarForm/AvatarForm.tsx
> +  const [imageError, setImageError] = useState<boolean>(false);
`<boolean>` is redundant here

2022-08-18 07:07 UTC, Daboo1998 commented on src/scenes/widgets/pages/ProfileWidget/components/templates/UserProfileView/UserProfileView.tsx
> +                  }}
```suggestion
                  onClick={grabATable}
```

2022-08-18 07:07 UTC, Daboo1998 commented on src/scenes/widgets/stores/ProfileStore/ProfileStore.ts
> +      isProfileEdit: false
Maybe `isEditingProfile`, something more like a verb

2022-08-18 07:35 UTC, PAKovalev requested changes

2022-08-18 07:35 UTC, PAKovalev commented on src/core/models/OnlineUsersList/OnlineUsersList.ts
> +    get isLoading() {
`get isLoading(): boolean {`

2022-08-18 07:35 UTC, PAKovalev commented on src/scenes/widgets/pages/ProfileWidget/components/templates/MyProfileEditor/MyProfileEditor.styled.ts
> +  width: 78.22px;
78

2022-08-18 07:35 UTC, PAKovalev commented on src/scenes/widgets/pages/ProfileWidget/components/templates/MyProfileEditor/MyProfileEditor.tsx
> +    UnityService.setKeyboardControl(false);
unityService

2022-08-18 07:35 UTC, PAKovalev commented on src/scenes/widgets/stores/ProfileStore/ProfileStore.ts
> +      get fetchSpaceIsDone() {
`: boolean`

2022-08-18 08:40 UTC, PAKovalev approved these changes

2022-08-18 08:59 UTC, Daboo1998 approved these changes

2022-08-18 09:34 UTC, merged