Error handling
momentum-xyz/ui-client pull request #187
Opened 2022-08-18 07:30 UTC by dmitry-yudakov

The changes are for handling system-wide errors like Disconnected from Unity or Under Maintenance response, perhaps some other too. It's a Draft for the moment, we need to discuss the selected approach.

There's a new Scene replacing old disconnected.html file used for both errors.

Related Issues:
https://app.zenhub.com/workspaces/refinement-board-6233550985ac53001daa2884/issues/momentum-xyz/bugs-and-features/1650

https://app.zenhub.com/workspaces/refinement-board-6233550985ac53001daa2884/issues/momentum-xyz/bugs-and-features/1638

2022-08-19 13:57 UTC, PAKovalev approved these changes

2022-08-19 15:07 UTC, Daboo1998 requested changes

2022-08-19 16:13 UTC, dmitry-yudakov commented on src/ui-kit/templates/SystemWideError/SystemWideError.tsx
> +  text: string | string[];
Yep, good note. Or maybe remove translation from within the component :) Still not sure if it was a good solution.

It will probably work even with translated texts passed, but the clearer the better .

I'm ok to rename it, let's discuss it on Monday while we're all online.

2022-08-22 07:50 UTC, Daboo1998 commented on src/ui-kit/templates/SystemWideError/SystemWideError.tsx
> +  text: string | string[];
Yeah good point and idea

2022-08-22 08:56 UTC, dmitry-yudakov commented on src/shared/services/i18n/locales/en-gb.ts
> +    },
Moved somethingWentWrong to errors section and renamed systemWideError to systemMessages

2022-08-22 08:58 UTC, dmitry-yudakov commented on src/ui-kit/templates/SystemWideError/SystemWideError.tsx
> +  text: string | string[];
We had a quick chat with @PAKovalev and agreed I'll change it to accept translated texts directly in this component to make it a bit simpler. It still uses translation for Refresh button internally though, maybe we'll change it in the future.

2022-08-22 09:09 UTC, merged