Feature/wb 12/world naming input form panel
momentum-xyz/ui-client pull request #232
Opened 2022-09-01 15:15 UTC by Daboo1998

2022-09-01 15:32 UTC, PAKovalev requested changes

2022-09-01 15:32 UTC, PAKovalev commented on src/api/constants/app.variables.ts
> +  BACKEND_V4_ENDPOINT_URL: 'https://dev.odyssey.ninja/api/v4',
it must come from backend.

2022-09-01 15:32 UTC, PAKovalev commented on src/scenes/App.tsx
> +        <Redirect
if (!sessionStore.oidcConfig && pathname === ROUTES.worldBuilder.base) {
  ....
} 

if (!sessionStore.oidcConfig) {
  ....
}

2022-09-01 15:32 UTC, PAKovalev commented on src/scenes/App.tsx
> +                isWorldBuilder={pathname.includes(ROUTES.worldBuilder.base)}
Don't use isWorldBuilder name

2022-09-01 15:32 UTC, PAKovalev commented on src/scenes/widgets/Widgets.tsx
> +  isWorldBuilder?: boolean;
??

2022-09-01 15:32 UTC, PAKovalev commented on src/scenes/widgets/Widgets.tsx
> -          <ToolbarIcon
I don't like this `mix`

2022-09-01 15:32 UTC, PAKovalev commented on src/scenes/widgets/pages/ProfileMenuWidget/ProfileMenuWidget.tsx
> +  isWorldBuilder?: boolean;
It is bad.

2022-09-01 15:32 UTC, PAKovalev commented on src/scenes/widgets/pages/ProfileMenuWidget/components/Menu/Menu.tsx
> +    document.location.href = isWorldBuilder ? ROUTES.worldBuilder.base : ROUTES.base;
?

2022-09-01 15:32 UTC, PAKovalev commented on src/scenes/widgets/pages/ProfileMenuWidget/components/Menu/Menu.tsx
> +        {!isWorldBuilder && (
No please.

2022-09-02 08:44 UTC, Daboo1998 commented on src/api/constants/app.variables.ts
> +  BACKEND_V4_ENDPOINT_URL: 'https://dev.odyssey.ninja/api/v4',
It's temporary, we remove it when all other BE EP will be migrated to V4 and we will use one BACKEND

2022-09-02 09:01 UTC, PAKovalev approved these changes

2022-09-02 09:50 UTC, dmitry-yudakov approved these changes

2022-09-02 09:54 UTC, merged