Feature/dev 25/invite people to space
momentum-xyz/ui-client pull request #242
Opened 2022-09-05 14:18 UTC by aminbksi

https://momentum.nifty.pm/l/_W7FY!D7!e2l

• If user joins the space, or accepts the invite and joins the space, the name of the user is removed from that list with people available for invite

2022-09-05 14:26 UTC, PAKovalev approved these changes

2022-09-06 08:41 UTC, PAKovalev requested changes

2022-09-06 08:41 UTC, PAKovalev commented on src/core/models/OnlineUsersList/OnlineUsersList.ts
> +        .filter((user) => user.uuid !== currentUser);
Remove second filter by current user.

2022-09-06 08:41 UTC, PAKovalev commented on src/ui-kit/organisms/OnlineUsersList/OnlineUsersList.tsx
> +      ...onlineUsersList.filteredPeople(excludedPeople, profile.uuid)
`...onlineUsersList.filteredPeople([...excludedPeople, profile.uuid])`

2022-09-06 08:50 UTC, Daboo1998 requested changes

2022-09-06 08:50 UTC, Daboo1998 commented on src/stores/MainStore/models/AgoraStore/AgoraStageModeStore/AgoraStageModeStore.ts
> +        });
No, audience should not contain speakers!

2022-09-06 08:50 UTC, Daboo1998 commented on src/stores/MainStore/models/AgoraStore/AgoraStore.ts
> +        ? self.agoraStageModeStore.audience.map((user) => user.uid.toString())
Here I would map both audience and users, and not combine speakers and audience in the audience field of `agoraStageModeStore`

2022-09-06 09:31 UTC, Daboo1998 approved these changes

2022-09-06 09:36 UTC, merged