Feature/wb 18/remove guest login when in world builder
momentum-xyz/ui-client pull request #249
Opened 2022-09-06 15:38 UTC by Daboo1998

2022-09-06 15:43 UTC, PAKovalev requested changes

2022-09-06 15:43 UTC, PAKovalev commented on src/scenes/auth/pages/WorldBuilderLoginPage/WorldBuilderLoginPage.tsx
> +                {web3ConnectorsFiltered.map((connector) => {
Only polkadot. No need to use `web3ConnectorsFiltered `

2022-09-06 15:43 UTC, PAKovalev commented on src/scenes/auth/pages/WorldBuilderLoginPage/WorldBuilderLoginPage.tsx
> +  useEffect(() => {
remove

2022-09-06 15:55 UTC, PAKovalev approved these changes

2022-09-07 07:19 UTC, aminbksi approved these changes

2022-09-07 07:33 UTC, merged