Upload emoji
momentum-xyz/ui-client pull request #269
Opened 2022-09-14 16:01 UTC by dmitry-yudakov

2022-09-16 16:38 UTC, dmitry-yudakov commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/templates/ManageEmojiPanel/ManageEmojiPanel.tsx
> +import {EmojiItem} from 'scenes/widgets/pages/EmojiWidget/components';
@PAKovalev Maybe I should move this EmojiItem to ui-kit?

2022-09-16 16:39 UTC, dmitry-yudakov commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/templates/ManageEmojiPanel/ManageEmojiPanel.tsx
> +                  // TODO send it to animations panel?
I'll remove this but want to check with the designers first :) It'd be cool to be able to test the emoji from the Space Admin screen directly and see how it looks.

2022-09-19 07:27 UTC, PAKovalev requested changes

2022-09-19 07:27 UTC, PAKovalev commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/DeleteEmojiDialog/DeleteEmojiDialog.tsx
> +      setIsLoading(true);
Use state of `Request` instead of `useState`.

2022-09-19 07:27 UTC, PAKovalev commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/UploadEmojiDialog/UploadEmojiDialog.tsx
> +  const [name, setName] = useState<string>('');
Use `react-hook-form`

2022-09-19 07:27 UTC, PAKovalev commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/UploadEmojiDialog/UploadEmojiDialog.tsx
> +  const [isLoading, setIsLoading] = useState(false);
Use state of `Request`

2022-09-19 07:27 UTC, PAKovalev commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/templates/ManageEmojiPanel/ManageEmojiPanel.tsx
> +import {EmojiItem} from 'scenes/widgets/pages/EmojiWidget/components';
Yeah

2022-09-19 07:27 UTC, PAKovalev commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/templates/ManageEmojiPanel/ManageEmojiPanel.tsx
> +  const [showUploadDialog, setShowUploadDialog] = useState(false);
use store for these fields

2022-09-19 07:27 UTC, PAKovalev commented on src/api/repositories/emojiRepository/emojiRepository.api.ts
> +export const uploadEmojiConfig: RequestInterface<UploadEmojiRequest, UploadEmojiResponse> = (
Why do use word `...Config`?)

2022-09-19 07:27 UTC, PAKovalev commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/templates/ManageEmojiPanel/ManageEmojiPanel.tsx
> +  const {
I would suggest to use `inline` destructuring.

2022-09-19 07:32 UTC, PAKovalev requested changes

2022-09-19 07:32 UTC, PAKovalev commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/templates/ManageEmojiPanel/ManageEmojiPanel.tsx
> +      emojiStore: {emojiDetailsList, uploadEmojiToSpace, deleteEmoji}
Make own store under SpaceAdmin scene.

2022-09-19 07:57 UTC, Daboo1998 requested changes

2022-09-19 07:57 UTC, Daboo1998 commented on src/api/repositories/emojiRepository/emojiRepository.api.endpoints.ts
> +  const BASE_URL_EMOJI = `${appVariables.BACKEND_ENDPOINT_URL}/emoji`;
I would split it to spaceEmojiRepository and emojiRepository

2022-09-19 07:57 UTC, Daboo1998 commented on src/api/repositories/emojiRepository/emojiRepository.api.types.ts
> +export interface UploadEmojiResponse {
Make sure to use spaces between blocks :)

2022-09-19 07:57 UTC, Daboo1998 commented on src/api/repositories/emojiRepository/emojiRepository.api.endpoints.ts
> +  const BASE_URL_EMOJI = `${appVariables.BACKEND_ENDPOINT_URL}/emoji`;
I would split it to spaceEmojiRepository and emojiRepository

2022-09-19 07:57 UTC, Daboo1998 commented on src/api/repositories/emojiRepository/emojiRepository.api.types.ts
> +export interface DeleteEmojiResponse {}
here too

2022-09-19 07:57 UTC, Daboo1998 commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/UploadEmojiDialog/UploadEmojiDialog.tsx
> +  const [name, setName] = useState<string>('');
+1

2022-09-19 07:57 UTC, Daboo1998 commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/UploadEmojiDialog/UploadEmojiDialog.tsx
> +  const [isLoading, setIsLoading] = useState(false);
+1

2022-09-19 07:57 UTC, Daboo1998 commented on src/scenes/widgets/stores/EmojiStore/EmojiStore.tsx
> +        {worldId: self.worldId}
what if `worldId` is `''`? Wouldn't it produce a 500? Maybe make a check at the start of the function?

2022-09-19 08:34 UTC, dmitry-yudakov commented on src/api/repositories/emojiRepository/emojiRepository.api.ts
> +export const uploadEmojiConfig: RequestInterface<UploadEmojiRequest, UploadEmojiResponse> = (
Historical reasons... :) I'll change it.

2022-09-19 08:35 UTC, dmitry-yudakov commented on src/api/repositories/emojiRepository/emojiRepository.api.types.ts
> +export interface UploadEmojiResponse {
They're a group :) But ok.

2022-09-19 08:37 UTC, dmitry-yudakov commented on src/scenes/widgets/stores/EmojiStore/EmojiStore.tsx
> +        {worldId: self.worldId}
It's set in init function and we should already have it there. And there's nothing meaningful I could do if it is '', so maybe error is ok.

2022-09-19 08:46 UTC, Daboo1998 commented on src/api/repositories/emojiRepository/emojiRepository.api.types.ts
> +export interface UploadEmojiResponse {
Still two blocks, you can separate blocks by comments like
```
// UPLOAD EMOJI
....
// ASSIGN EMOJI TO SPACE
...

```
etc.

2022-09-20 07:09 UTC, dmitry-yudakov commented on src/scenes/spaceAdmin/stores/ManageEmojiStore/ManageEmojiStore.ts
> +        throw new Error('Failed to upload emoji');
@PAKovalev  is that ok here? 
Checking the result of Request.send() and throwing error so it could be handled in the component.

2022-09-20 07:26 UTC, PAKovalev requested changes

2022-09-20 07:26 UTC, PAKovalev commented on src/scenes/spaceAdmin/stores/ManageEmojiStore/ManageEmojiStore.ts
> +        throw new Error('Failed to assign emoji to space');
Use state of `Request` instead `throw`

2022-09-20 07:26 UTC, PAKovalev commented on src/scenes/spaceAdmin/stores/ManageEmojiStore/ManageEmojiStore.ts
> +        throw new Error('Failed to delete emoji');
Use state of `Request` instead `throw`.

2022-09-20 07:26 UTC, PAKovalev commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/UploadEmojiDialog/UploadEmojiDialog.tsx
> +    try {
Use state of `Request` instead `try catch`.

2022-09-20 07:26 UTC, PAKovalev commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/DeleteEmojiDialog/DeleteEmojiDialog.tsx
> +    try {
Use state of `Request` instead `try catch`.

2022-09-20 07:26 UTC, PAKovalev commented on src/scenes/spaceAdmin/stores/ManageEmojiStore/ManageEmojiStore.ts
> +        throw new Error('Failed to upload emoji');
Yeah, if request is failed, result will be undefined.

2022-09-20 07:26 UTC, PAKovalev commented on src/scenes/spaceAdmin/stores/ManageEmojiStore/ManageEmojiStore.ts
> +    get isUploadPending() {
: boolean

2022-09-20 07:28 UTC, Daboo1998 approved these changes

2022-09-20 07:28 UTC, Daboo1998 commented on src/api/repositories/emojiRepository/emojiRepository.api.endpoints.ts
> +  const EMOJI_BASE_URL = `${appVariables.BACKEND_ENDPOINT_URL}/emoji`;
You could leave it as just `BASE_URL`

2022-09-20 07:28 UTC, Daboo1998 commented on src/api/repositories/spaceEmojiRepository/spaceEmojiRepository.api.endpoints.ts
> +  const SPACE_EMOJI_BASE_URL = `${appVariables.BACKEND_ENDPOINT_URL}/space-emoji`;
Just `BASE_URL` to make it consistent with other repos files

2022-09-20 07:44 UTC, Daboo1998 commented on src/scenes/widgets/pages/EmojiWidget/EmojiWidget.tsx
> +            <Emoji emoji={em} onClick={() => handleEmojiClick(em.id, em.unityUrl)} key={em.id} />
use full name `emoji` or `emojiDetails`

2022-09-20 08:27 UTC, PAKovalev approved these changes

2022-09-20 08:28 UTC, dmitry-yudakov commented on src/scenes/spaceAdmin/stores/ManageEmojiStore/ManageEmojiStore.ts
> +        throw new Error('Failed to delete emoji');
We agreed on returning boolean instead of throw

2022-09-20 08:28 UTC, dmitry-yudakov commented on src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/DeleteEmojiDialog/DeleteEmojiDialog.tsx
> +    try {
We agreed on returning boolean instead of throw

2022-09-20 08:32 UTC, merged