delete event error fix
momentum-xyz/ui-client pull request #270
Opened 2022-09-14 16:08 UTC by aminbksi

2022-09-14 16:12 UTC, Daboo1998 requested changes

2022-09-14 16:12 UTC, Daboo1998 commented on src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +      eventDeleted: false,
You don't need that, just use `removeEventRequest.isDone` where necessary

2022-09-14 16:17 UTC, Daboo1998 approved these changes

2022-09-15 06:49 UTC, PAKovalev approved these changes

2022-09-15 06:57 UTC, dmitry-yudakov approved these changes

2022-09-15 06:59 UTC, merged