Feature/module federation with craco
momentum-xyz/ui-client pull request #277
Opened 2022-09-20 15:04 UTC by Daboo1998

NOTE: DO NOT CHECK

It's just to show changes

2022-09-22 09:19 UTC, PAKovalev requested changes

2022-09-22 09:19 UTC, PAKovalev commented on src/core/utils/pluginLoader.utils.tsx
> +import {PluginLoaderInterface} from 'core/interfaces';
Move this file to shared folder.

2022-09-22 09:19 UTC, PAKovalev commented on src/core/utils/pluginLoader.utils.tsx
> +    return <h2>Not system specified</h2>;
i18n

2022-09-22 09:19 UTC, PAKovalev commented on src/core/utils/pluginLoader.utils.tsx
> +    <Suspense fallback="Loading Plugin">
use `ErrorBoundary`

2022-09-22 09:19 UTC, PAKovalev commented on src/core/utils/pluginLoader.utils.tsx
> +    <Suspense fallback="Loading Plugin">
i18n

2022-09-22 09:19 UTC, PAKovalev commented on src/scenes/collaboration/Collaboration.tsx
> +  useEffect(() => {
I would suggest to define a separate component under `collaboration/components` to have all stuff related to plugins

2022-09-22 09:19 UTC, PAKovalev commented on src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> +        subtitle="Miro document"
it is prop of PluginInterface

2022-09-22 09:19 UTC, PAKovalev commented on src/stores/ConfigStore/ConfigStore.ts
> +        window['env'] = appVariables;
Make a TODO.

2022-09-22 10:31 UTC, PAKovalev requested changes

2022-09-22 10:31 UTC, PAKovalev commented on src/core/constants/pluginList.constant.ts
> +    url: appVariables.IS_DEV_ENVIRONMENT
make helper

2022-09-22 10:33 UTC, PAKovalev requested changes

2022-09-22 10:33 UTC, PAKovalev commented on src/stores/ConfigStore/ConfigStore.ts
> +        window['env'] = {
TODO.

2022-09-22 10:34 UTC, Daboo1998 commented on src/core/utils/pluginLoader.utils.tsx
> +import {PluginLoaderInterface} from 'core/interfaces';
which file? PluginLoaderInterface or pluginLoader.utils.tsx ?

2022-09-22 10:56 UTC, dmitry-yudakov commented on src/core/constants/pluginList.constant.ts
> +    iconName: 'miro',
I'd suggest:

```
{
  id: 'miro',
  title: 'Miro Board', // for top bar and everywhere else
  iconUrl: 'https://...' // not sure here how it should be stored but it won't be in our iconset
  iconName: 'icon-name-from-iconset', // we could use iconUrl or iconName, but it will probably be url unless the iconset is very rich

2022-09-22 10:57 UTC, dmitry-yudakov commented on src/core/constants/pluginList.constant.ts
> +    path: ROUTES.collaboration.miro,
I'm not really sure about these paths - we could use like plugin id in url if the plugin extends the space tabs panel. But IMO it's not correct to allow plugin provide this info.

2022-09-22 11:01 UTC, dmitry-yudakov commented on src/core/utils/pluginLoader.utils.tsx
> +  const {ready, failed} = useDynamicScript(module && url);
I think it should be loaded a bit differently - not as Component and hook. The module will need to provide more than one view perhaps - potentially Tab view, Widget, Space config panel, World Config panel. The configs could be declarative at the beginning but in future we'll probably allow more flexibility.

2022-09-22 11:03 UTC, dmitry-yudakov commented on src/core/utils/pluginLoader.utils.tsx
> +    <Suspense fallback="Loading Plugin">
The plugins will probably have to provide some translation object if they're to support several languages. Right now for simplicity I'd suggest to only leave plain english text as is.

2022-09-22 11:12 UTC, Daboo1998 commented on src/scenes/collaboration/Collaboration.tsx
> +  useEffect(() => {
But the problem is that both navigation tabs and pages depend on that

2022-09-22 11:17 UTC, Daboo1998 commented on src/core/constants/pluginList.constant.ts
> +    url: appVariables.IS_DEV_ENVIRONMENT
I would not focus on pluginList cause it will come from backend anyways

2022-09-22 11:18 UTC, Daboo1998 commented on src/core/utils/pluginLoader.utils.tsx
> +    <Suspense fallback="Loading Plugin">
This is not part of plugin, so @PAKovalev is right

2022-09-22 11:19 UTC, Daboo1998 commented on src/core/constants/pluginList.constant.ts
> +    iconName: 'miro',
name: 'miro_plugin' is strictly related to MF, so it has to stay that way (I can only change fields name)

2022-09-22 11:30 UTC, dmitry-yudakov commented on src/core/constants/pluginList.constant.ts
> +    iconName: 'miro',
Yeah, it's ok to have _plugin suffix for now.

2022-09-22 11:56 UTC, Daboo1998 commented on src/core/utils/pluginLoader.utils.tsx
> +    <Suspense fallback="Loading Plugin">
on error I think deals with that and ErrorBoundary solution is not compatible with hooks

2022-09-22 11:57 UTC, Daboo1998 commented on src/core/constants/pluginList.constant.ts
> +    iconName: 'miro',
For the icons, we would have to refactor the IconSvg component

2022-09-22 12:09 UTC, Daboo1998 commented on src/core/utils/pluginLoader.utils.tsx
> +  const {ready, failed} = useDynamicScript(module && url);
Hmm I don't know, as you can basically use this PluginLoader to load components from different list. Widget List for example and each Widget is a component

2022-09-22 12:10 UTC, Daboo1998 commented on src/scenes/collaboration/Collaboration.routes.tsx
> +      main: () => (
To be discussed. Might be a config coming from BE or it can be som other component exposed from the plugin itself.

2022-09-22 12:12 UTC, Daboo1998 commented on src/core/utils/pluginLoader.utils.tsx
> +  const {ready, failed} = useDynamicScript(module && url);
A plugin can also expose more than one module, it can be ./App, or ./Widget or ./TabView etc.

2022-09-22 12:55 UTC, PAKovalev commented on src/core/utils/pluginLoader.utils.tsx
> +import {PluginLoaderInterface} from 'core/interfaces';
pluginLoader.utils.tsx

2022-09-22 13:02 UTC, PAKovalev requested changes

2022-09-22 13:02 UTC, PAKovalev commented on src/scenes/collaboration/Collaboration.tsx
> +          plugins,
why?)

2022-09-22 13:51 UTC, PAKovalev approved these changes

2022-09-23 07:07 UTC, dmitry-yudakov commented on craco.config.js
> +        }
Maybe we should also include axios here? It will probably be pretty common for a plugin to make custom requests to some external service.

Just a thought, not blocking right now.

2022-09-23 07:41 UTC, dmitry-yudakov approved these changes

2022-09-23 07:50 UTC, merged