Implemented actions (WIP)
momentum-xyz/ui-client pull request #283
Opened 2022-09-23 13:48 UTC by Daboo1998

2022-09-23 14:44 UTC, PAKovalev requested changes

2022-09-23 14:44 UTC, PAKovalev commented on src/core/constants/pluginList.constant.ts
> +export const COLLABORATION_PLUGIN_LIST: (
Move this to store file.

2022-09-23 14:44 UTC, PAKovalev commented on src/core/interfaces/pluginProps.interface.ts
> +export interface PluginPropsInterface {
CorePluginPropsInterface

2022-09-23 14:44 UTC, PAKovalev commented on src/core/interfaces/pluginProps.interface.ts
> +export interface CollaboarationPluginPropsInterface extends PluginPropsInterface {
SpacePluginPropsInterface

2022-09-23 14:44 UTC, PAKovalev commented on src/core/interfaces/plugin.interface.ts
> +  props?: PluginPropsInterface;
Remove this field.

2022-09-23 14:44 UTC, PAKovalev commented on src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> -  subtitle?: string;
Remove `PropsInterface`. Plugin key is in the url. Get plugin from store by key.

2022-09-23 14:44 UTC, PAKovalev commented on src/shared/hooks/pluginLoader.tsx
> +  useEffect(() => {
I feel we can remove this.

2022-09-23 14:44 UTC, PAKovalev commented on src/scenes/collaboration/Collaboration.tsx
> +    pluginsStore.init(theme, space?.isAdmin ?? false, spaceId);
`pluginsStore.init(spaceId);`

2022-09-23 14:44 UTC, PAKovalev commented on src/scenes/collaboration/stores/CollaborationPluginsStore/models/CollaborationPlugin/CollaborationPlugin.ts
> +const CollaborationPlugin = types.model('CollaborationPlugin', {
SpacePlugin

2022-09-26 07:38 UTC, Daboo1998 commented on src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> -  subtitle?: string;
But what about subtitle and request props?

2022-09-26 07:40 UTC, Daboo1998 commented on src/shared/hooks/pluginLoader.tsx
> +  useEffect(() => {
it was for debugging, so yes we can now

2022-09-26 07:41 UTC, Daboo1998 commented on src/scenes/collaboration/stores/CollaborationPluginsStore/CollaborationPluginsStore.ts
> +          theme,
ah you mean they should be passed in component not store, I get it now

2022-09-26 07:44 UTC, Daboo1998 commented on src/scenes/collaboration/Collaboration.tsx
> +  }, [history, pluginsStore, space?.isAdmin, spaceId, theme]);
I guess some leftover, Ill remove

2022-09-26 07:46 UTC, Daboo1998 commented on src/scenes/collaboration/Collaboration.tsx
> +              <CollaborationPluginPage plugin={plugin} request={pluginRequest} />
But plugin needs some more information than just plugin name and path, like subtitle, isAdmin etc

2022-09-26 07:49 UTC, Daboo1998 commented on src/scenes/collaboration/stores/CollaborationPluginsStore/models/CollaborationPlugin/CollaborationPlugin.ts
> +const CollaborationPlugin = types.model('CollaborationPlugin', {
I would agree but the plugin is in Collaboration so it more consistent to name it CollabprationPlugin

2022-09-28 10:16 UTC, closed without merging