Feature/mir 21/move miro plugin to the mono repo
momentum-xyz/ui-client pull request #288
Opened 2022-09-28 14:49 UTC by Daboo1998

2022-09-28 15:46 UTC, PAKovalev commented on packages/miro-plugin/src/bootstrap.tsx
> +import React from 'react';
I would suggest `plugin-miro` instead of `miro-plugin`. It is not important, but all plugins folders will be together. It will be easy to find something if we have lots of plugins.

2022-09-28 15:47 UTC, PAKovalev commented on packages/miro-plugin/src/bootstrap.tsx
> +import 'static/styles/index.css';
is there no eslint error here?

2022-09-28 15:48 UTC, dmitry-yudakov commented on packages/miro-plugin/src/pages/MiroBoardPage/components/templates/MiroBoard/MiroBoard.tsx
> +  const {t} = useTranslation();
Will useTranslation actually work in plugin? Does it make sense to have it at this point?

2022-09-28 15:48 UTC, PAKovalev commented on packages/miro-plugin/src/core/contexts/index.ts
> +export * from './GloabalPropsContext';
typo

2022-09-28 15:50 UTC, PAKovalev commented on packages/miro-plugin/public/index.html
> +<!DOCTYPE html>
do we need public folder at all?

2022-09-28 15:52 UTC, PAKovalev commented on packages/miro-plugin/src/core/models/Request/RequestModel.ts
> +import {types, flow} from 'mobx-state-tree';
{/* TODO: Get from @momentum/core */}

2022-09-28 15:54 UTC, PAKovalev commented on packages/ui-kit/src/themes/themes.config.ts
> +import {ThemeInterface} from '../interfaces';
why do need to have this? theme comes from props of plugin.

2022-09-28 15:55 UTC, dmitry-yudakov commented on packages/miro-plugin/package.json
> +    "react-router-dom": "^6.4.0",
We're using "react-router-dom": "^5.2.0" in the main app and I wonder if it's a bad idea to mix them like this. Perhaps some common packages like react/react-dom/react-router/mobx/etc we should later put to the main `package.json`

2022-09-28 15:57 UTC, dmitry-yudakov commented on packages/ui-kit/src/themes/themes.config.ts
> +import {ThemeInterface} from '../interfaces';
It should be taken from `@momentum/ui-kit` I guess?

2022-09-29 07:26 UTC, Daboo1998 commented on packages/miro-plugin/src/bootstrap.tsx
> +import 'static/styles/index.css';
Seems Eslint does not work. Will fix

2022-09-29 10:23 UTC, Daboo1998 commented on packages/miro-plugin/public/index.html
> +<!DOCTYPE html>
yes to be able to run plugin independently, I think we discussed it already🙂

2022-09-29 10:25 UTC, Daboo1998 commented on packages/ui-kit/src/themes/themes.config.ts
> +import {ThemeInterface} from '../interfaces';
yes but don't we need to define the props

2022-09-29 10:27 UTC, Daboo1998 commented on packages/miro-plugin/src/pages/MiroBoardPage/components/templates/MiroBoard/MiroBoard.tsx
> +  const {t} = useTranslation();
yes, cause also plugin has its own translations

2022-09-29 10:31 UTC, Daboo1998 commented on packages/miro-plugin/src/bootstrap.tsx
> +import React from 'react';
We can also make structure like this:
```
|- packages
   |-app
   |- libs
       |- ui-kit
       |- core
       ...
   |-plugins
       |-miro
       ...
```

But lets discuss it later, other than that `miro-plugin` sounds better if you read it than `plugin-miro`

2022-09-29 10:34 UTC, Daboo1998 commented on packages/miro-plugin/src/bootstrap.tsx
> +        spaceId="b860dc5a-578a-4d05-b526-2a92e866d975"
In general, bootstrap is used to run the plugin independently. The host app doesn't use bootstrap at all. So we might discuss adding an BE endpoint to be called here, however we need then a whole interface Ito select a space from a list and then show the Miro board. But that's out of scope for now. So for now `spaceId="b860dc5a-578a-4d05-b526-2a92e866d975"` is for illustration purposes.

2022-09-29 10:36 UTC, Daboo1998 commented on packages/miro-plugin/package.json
> +    "react-router-dom": "^6.4.0",
Yes idk why the different version is here. will use  "^5.2.0"

2022-09-29 11:05 UTC, PAKovalev commented on packages/ui-kit/src/themes/themes.config.ts
> +import {ThemeInterface} from '../interfaces';
theme comes from props. it's just fields. Remove theme props at all.

2022-09-29 11:07 UTC, PAKovalev commented on packages/miro-plugin/src/bootstrap.tsx
> +        spaceId="b860dc5a-578a-4d05-b526-2a92e866d975"
I don't understand why do we need to hardcode theme and spaceId.

2022-09-29 11:10 UTC, PAKovalev commented on packages/ui-kit/src/themes/themes.config.ts
> +import {ThemeInterface} from '../interfaces';
ThemeInterface will come from `core`.

2022-09-29 11:32 UTC, dmitry-yudakov commented on packages/miro-plugin/src/bootstrap.tsx
> +import React from 'react';
I think one directory level of packages is enough and we shouldn't overdesign.

But I also think `plugin-miro` and later `plugin-google`, etc will be better for numerous reasons. 
Either way it's better be settled before the deploy, etc.

2022-09-29 11:49 UTC, PAKovalev approved these changes

2022-09-29 11:59 UTC, Daboo1998 commented on packages/miro-plugin/src/bootstrap.tsx
> +import React from 'react';
Let's discuss it in our meeting today

2022-09-29 14:29 UTC, Daboo1998 commented on packages/miro-plugin/craco.config.js
> +            // './WidgetApp': './src/[app file name]'
This btw, might be used later for plugin developers to make it easier for them.

2022-09-30 07:23 UTC, dmitry-yudakov commented on packages/miro-plugin/craco.config.js
> +            // './WidgetApp': './src/[app file name]'
Note, guys, that plugins in future could be written without React if we want to support wide range of 3rd party devs.

2022-09-30 07:25 UTC, Daboo1998 commented on packages/miro-plugin/craco.config.js
> +            // './WidgetApp': './src/[app file name]'
yeah but you can still expose a component even made with non react, just probably we would have to handle somehow on the host side.

2022-09-30 07:30 UTC, PAKovalev requested changes

2022-09-30 07:30 UTC, PAKovalev commented on packages/app/src/core/enums/pluginType.enum.ts
> +  SPACE = './SpaceApp',
`SPACE = 'SPACE'`

2022-09-30 07:30 UTC, PAKovalev commented on packages/app/src/shared/hooks/pluginLoader.tsx
> +    return React.lazy(loadComponent(name, pluginType));
`return React.lazy(loadComponent(name, `./{pluginType}App`));`

2022-09-30 08:09 UTC, Daboo1998 commented on packages/app/src/shared/hooks/pluginLoader.tsx
> +    return React.lazy(loadComponent(name, pluginType));
Provided I do what you suggested in previous comment, `./{pluginType}App` will produce `./SPACEApp`

2022-09-30 08:10 UTC, Daboo1998 commented on packages/app/src/core/enums/pluginType.enum.ts
> +  SPACE = './SpaceApp',
`SPACE = 'Space'` maybe? look at my answer to your next comment.

2022-09-30 09:10 UTC, PAKovalev commented on packages/app/src/core/enums/pluginType.enum.ts
> +  SPACE = './SpaceApp',
ok

2022-09-30 09:10 UTC, PAKovalev commented on packages/app/src/shared/hooks/pluginLoader.tsx
> +    return React.lazy(loadComponent(name, pluginType));
ok

2022-09-30 09:11 UTC, dmitry-yudakov approved these changes

2022-09-30 09:16 UTC, PAKovalev approved these changes

2022-09-30 09:17 UTC, merged