Trying new approach
momentum-xyz/ui-client pull request #308
Opened 2022-10-06 15:14 UTC by Daboo1998

2022-10-06 15:18 UTC, PAKovalev requested changes

2022-10-06 16:30 UTC, Daboo1998 commented on packages/sdk/src/interfaces/plugin.interface.ts
> +  SpaceApp?: React.FC<SpacePluginPropsInterface>;
Well we need to differentiate somehow, plugin is the whole thing while each part (Space, Widget and Home) is an app. We need to mayve change PluginType to AppType not to confuse

2022-10-07 06:56 UTC, dmitry-yudakov approved these changes
I like it, I think it's a step in the right direction.

2022-10-07 06:56 UTC, dmitry-yudakov commented on packages/app/src/shared/hooks/pluginLoader.tsx
> +  (scope: string, pluginType: PluginTypeEnum) =>
It's ok this way for the moment but in future I'd leave this function to return the whole plugin object and inside this object we would look for Space, Widget, etc components but possibly also for Space Tab Icon component or Widget Button component or render function.

2022-10-07 06:56 UTC, dmitry-yudakov commented on packages/sdk/src/interfaces/plugin.interface.ts
> +  SpaceApp?: React.FC<SpacePluginPropsInterface>;
Could be SpaceTabContent or WidgetComponent. I don't think any Type is needed at all.

2022-10-07 07:08 UTC, Daboo1998 commented on packages/sdk/src/interfaces/plugin.interface.ts
> +  SpaceApp?: React.FC<SpacePluginPropsInterface>;
No we have a typo for the FE to use when loading. Not talking about the component itself

2022-10-07 07:31 UTC, dmitry-yudakov commented on packages/sdk/src/interfaces/plugin.interface.ts
> +  SpaceApp?: React.FC<SpacePluginPropsInterface>;
Well, it's the implementation detail of the host app. The interface which will be used by 3rd party devs should be clear for them.

2022-10-07 07:37 UTC, Daboo1998 commented on packages/sdk/src/interfaces/plugin.interface.ts
> +  SpaceApp?: React.FC<SpacePluginPropsInterface>;
we need to defrentiate the whole thing from each part, so we need to think how we want to name each. We cannot call the whole app and its parts a plugin

2022-10-07 11:34 UTC, merged