Persistent Chat -> develop
momentum-xyz/ui-client pull request #322
Opened 2022-10-11 14:41 UTC by dmitry-yudakov

Old TextChat is replaced with external service https://getstream.io/ - it's very advanced Chat solution providing among the ton of other stuff the history of messages that we lacked so much.

We stripped it to the bare minimum for the moment to simplify the styling.

It's not clear whether it will be used in the future, so the old TextChat is not removed from the codebase.

https://momentum.nifty.pm/l/rgp74fYLqB

#DEV-100

2022-10-11 14:59 UTC, PAKovalev requested changes

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/api/constants/app.variables.ts
> +  APP_VERSION: 'v0.21.0',
We can set 0.22.0 btw.

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.endpoints.ts
> +    token: `:spaceId/channel-token`,
`token: '${BASE_URL}/:spaceId/channel-token'`
`leave: '${BASE_URL}/:spaceId/leave'`

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.ts
> +  const url = `${streamChatRepositoryApiEndpoints().baseURL}/${path}`;
You can remove `url`, see previous comment.

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.ts
> +  const url = `${streamChatRepositoryApiEndpoints().baseURL}/${path}`;
You can remove `url`, see previous comment.

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/Collaboration.tsx
> +        if (!streamChatStore.isLoggedOn) {
Can we move this to the `joinMeetingSpace` function?

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/components/StreamChat/StreamChat.styled.ts
> +    font-size: 13px;
use const `--font-size-s`

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/components/StreamChat/StreamChat.tsx
> +class ErrorBoundaries extends Component<unknown, StateInterface> {
Move to separate file. 1 file === 1 component.

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/components/StreamChat/StreamChat.tsx
> +                <MessageInput disableMentions={true} grow={true} maxRows={5} />
`<MessageInput disableMentions grow maxRows={5} />`

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/pages/DashboardPage/components/templates/Dashboard/Dashboard.tsx
> +      {textChatIsOpen && streamChatStore.client && streamChatStore.currentChannel && (
Make a view under store.

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/pages/GoogleDrivePage/GoogleDrivePage.tsx
> +        {streamChatStore.textChatDialog.isOpen &&
Use `view`

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/pages/LiveStreamPage/LiveStreamPage.tsx
> +        {streamChatStore.textChatDialog.isOpen &&
Use `view`

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/pages/MiroBoardPage/MiroBoardPage.tsx
> +        {streamChatStore.textChatDialog.isOpen &&
Use `view`

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/pages/ScreenSharePage/ScreenSharePage.tsx
> +        {streamChatStore.textChatDialog.isOpen &&
Use `view`

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/pages/StageModePage/components/templates/StageModeGuest/StageModeGuest.tsx
> +        {streamChatStore.textChatDialog.isOpen &&
Use `view`

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/stores/StreamChatStore/StreamChatStore.ts
> +            // it breaks the app when we try to init in another space or world chat
Can we remove?

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/widgets/pages/WorldChatWidget/WorldChatWidget.tsx
> +  useEffect(() => {
Why do we pause unity?

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/components/StreamChat/StreamChat.tsx
> +import {CustomMessageInput} from './components/CustomMessageInput';
`import {CustomMessageInput} from './components';` will look better.

2022-10-11 14:59 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/pages/DashboardPage/components/templates/Dashboard/Dashboard.tsx
> +import {StreamChat} from 'scenes/collaboration/components/StreamChat';
`import {StreamChat} from 'scenes/collaboration/components';` will look better

2022-10-11 15:00 UTC, dmitry-yudakov commented on packages/app/src/api/constants/app.variables.ts
> +  APP_VERSION: 'v0.21.0',
It's beyond the scope of this PR :)

2022-10-11 15:02 UTC, dmitry-yudakov commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.ts
> +  const url = `${streamChatRepositoryApiEndpoints().baseURL}/${path}`;
@jor-rit did this - apparently this way you can put something like `https://localhost:4000` as BASE_URL and it won't get replaced by `generate_path()` :) 
I understand the motivation of your remark but maybe it's good to stay this way for the flexibility of local testing?

2022-10-11 15:05 UTC, dmitry-yudakov commented on packages/app/src/scenes/widgets/pages/WorldChatWidget/WorldChatWidget.tsx
> +  useEffect(() => {
I think Unity somehow grabs all the input from the keyboard and you cannot type in the chat :)

2022-10-11 15:15 UTC, Daboo1998 requested changes

2022-10-11 15:15 UTC, Daboo1998 commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.ts
> +  const url = `${streamChatRepositoryApiEndpoints().baseURL}/${path}`;
you can always change BASE_URL to localhost ;)

2022-10-11 15:15 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/components/StreamChat/StreamChat.styled.ts
> +            font-size: 13px;
use const --font-size-s

2022-10-11 15:15 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/components/StreamChat/StreamChat.tsx
> +class ErrorBoundaries extends Component<unknown, StateInterface> {
Use existing ErrorBoundary from ui-kit

2022-10-11 15:15 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/stores/RootCollaborationStore.ts
> +        self.streamChatStore.resetModel();
can't you do that inside `deinit` function?

2022-10-11 15:15 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/stores/StreamChatStore/StreamChatStore.ts
> +      const timeNow = new Date();
won't it be better to use that inside actions or define action that does that? I think the time won't be now everytime you call functions that use it. Time will only be initialled when the model is initialised I think

2022-10-11 15:15 UTC, Daboo1998 commented on packages/app/src/scenes/widgets/pages/ProfileWidget/components/templates/MyProfileEditor/MyProfileEditor.tsx
> +        });
maybe change it to use awaits instead of then?

2022-10-11 15:20 UTC, PAKovalev commented on packages/app/src/scenes/widgets/pages/WorldChatWidget/WorldChatWidget.tsx
> +  useEffect(() => {
We can avoid it. See People or Explore panels on Home Page : )

2022-10-11 15:30 UTC, dmitry-yudakov commented on packages/app/src/api/constants/app.variables.ts
> +  APP_VERSION: 'v0.21.0',
It's all Jorrit, I'm but a mere FE technician here ;)

2022-10-11 15:36 UTC, Daboo1998 commented on packages/app/src/api/constants/app.variables.ts
> +  APP_VERSION: 'v0.21.0',
Ah its master Jorrit, ok then ignore it

2022-10-11 15:52 UTC, dmitry-yudakov commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.ts
> +  const url = `${streamChatRepositoryApiEndpoints().baseURL}/${path}`;
Yeah, you just copy-paste something from the next component but these guys become all judgemental on you 😆

2022-10-11 16:00 UTC, dmitry-yudakov commented on packages/app/src/api/constants/app.variables.ts
> +  APP_VERSION: 'v0.21.0',
should we take it from the tag via some env variable?

2022-10-11 16:43 UTC, dmitry-yudakov commented on packages/app/src/scenes/collaboration/components/StreamChat/StreamChat.tsx
> +class ErrorBoundaries extends Component<unknown, StateInterface> {
I **PROMISE** to use the ui-kit one after the merge to `develop-plugins` - it has external dependency and potential merge conflict.

2022-10-12 07:09 UTC, PAKovalev commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.ts
> +  const url = `${streamChatRepositoryApiEndpoints().baseURL}/${path}`;
just const url = `generatePath(streamChatRepositoryApiEndpoints().token, {spaceId});`

2022-10-12 07:13 UTC, PAKovalev requested changes

2022-10-12 07:13 UTC, PAKovalev commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.ts
> +  const url = `${streamChatRepositoryApiEndpoints().baseURL}/${path}`;
@jor-rit `appVariables.BACKEND_ENDPOINT_URL` has relative path without host. Is not it?

2022-10-12 07:33 UTC, dmitry-yudakov commented on packages/app/src/scenes/collaboration/stores/StreamChatStore/StreamChatStore.ts
> +            // it breaks the app when we try to init in another space or world chat
Yes, I can remove the comment but it's an important piece of knowledge for this code and its future development :)

2022-10-12 08:33 UTC, jor-rit commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.ts
> +  const url = `${streamChatRepositoryApiEndpoints().baseURL}/${path}`;
nope, it's a absolute url. By default, if you run ui-client on localhost it points to our dev env API domain. That works as long as the host string doesn't contain a ':'

2022-10-12 09:13 UTC, dmitry-yudakov commented on packages/app/src/scenes/collaboration/stores/StreamChatStore/StreamChatStore.ts
> +      const timeNow = new Date();
Yep, and that's exactly what I need here ;)

It's for showing the unread messages indication though this part will need to be improved in future.

2022-10-12 09:33 UTC, dmitry-yudakov commented on packages/app/src/scenes/widgets/pages/ProfileWidget/components/templates/MyProfileEditor/MyProfileEditor.tsx
> +        });
It's actually a larger piece of code having some toast notifications after that but I'd say it's out of scope of this PR.

Maybe we could take a look at things like this (the whole FE team) from time to  and consider the best approach. @PAKovalev

2022-10-12 09:36 UTC, dmitry-yudakov commented on packages/app/src/scenes/widgets/pages/WorldChatWidget/WorldChatWidget.tsx
> +  useEffect(() => {
done, thx

2022-10-12 09:36 UTC, dmitry-yudakov commented on packages/app/src/scenes/collaboration/components/StreamChat/StreamChat.styled.ts
> +            font-size: 13px;
yep, changed it

2022-10-12 10:37 UTC, Daboo1998 approved these changes
I don't like a few things about it, but it seems there are no ways around it now, so I approve

2022-10-12 10:37 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/components/StreamChat/StreamChat.tsx
> +class ErrorBoundaries extends Component<unknown, StateInterface> {
Add a todo then

2022-10-12 10:54 UTC, PAKovalev approved these changes

2022-10-12 15:39 UTC, dmitry-yudakov commented on packages/app/src/api/repositories/streamChatRepository/streamChatRepository.api.ts
> +  const url = `${streamChatRepositoryApiEndpoints().baseURL}/${path}`;
We decided to leave it like this and think about a better strategy for the future. 
This problem is across the whole codebase and if we decide to put a port into some of the API bases of the world config, we might get in trouble.

2022-10-13 06:14 UTC, merged