Feature/mir 17/implement use of generic attributes api in miro plugins
momentum-xyz/ui-client pull request #365
Opened 2022-10-24 15:13 UTC by Daboo1998

2022-10-24 15:34 UTC, PAKovalev approved these changes

2022-10-24 16:08 UTC, aminbksi approved these changes

2022-10-25 11:41 UTC, dmitry-yudakov approved these changes
It's a good next step.

I suggested some small improvements and some bigger improvements. 

The bigger one is moving plugin state logic into separate plugin instance store - it would deal with loading/updating/monitoring the shared state thus making the plugin pluggable into more than just space.

2022-10-25 11:41 UTC, dmitry-yudakov commented on packages/plugin_miro/src/pages/MiroBoardPage/MiroBoardPage.tsx
> +    init(['board']);
`init({ fields: ['board'] })` would be better here

2022-10-25 11:41 UTC, dmitry-yudakov commented on packages/app/src/stores/MainStore/models/PluginsStore/PluginsStore.ts
> +      );
Perhaps at least 

```js
const pluginData = yield Promise.all([
  self.pluginMetadataRequest.send(),
  self.pluginOptionsRequest.send()
])
```

2022-10-25 11:41 UTC, dmitry-yudakov commented on packages/sdk/src/interfaces/pluginProps.interface.ts
> +  setPluginSpaceStateSubField: <V>(
As a plugin developer I would be terrified seeing this `setPluginSpaceStateSubField` and would give up on the second camelCase step :)

In future I would go with firebase-styled `set/update` functions and hide all the subfields details in the implementation.

```
const updateSharedState = (path: string, data: any) => {
  if(typeof data === 'object') {
    // traverse data and make backend calls for setSubField(path, innerPath, value), perhaps with Promise.all
  } else {
    // call set subfield
  }
}
```

And further in future it would go to the backend

2022-10-26 07:38 UTC, PAKovalev requested changes

2022-10-26 07:38 UTC, PAKovalev commented on packages/app/src/api/repositories/spaceRepository/spaceRepository.api.ts
> +export const getSpaceOptions: RequestInterface<GetSpaceOptionsRequest, GetSpaceOptionsResponse> = (
Move all of this to `spaceAttributeRepository` because `spaceAttributeRepository` is pure repo. It is used only by another repos. `spaceRepository` should have only own interfaces which will be transformed for `spaceAttributeRepository`.

2022-10-26 08:27 UTC, Daboo1998 commented on packages/sdk/src/interfaces/pluginProps.interface.ts
> +  setPluginSpaceStateSubField: <V>(
Unfortunately Antons vision blocks us from doing it

2022-10-26 12:24 UTC, Daboo1998 commented on packages/app/src/api/repositories/spaceRepository/spaceRepository.api.ts
> +export const getSpaceOptions: RequestInterface<GetSpaceOptionsRequest, GetSpaceOptionsResponse> = (
Well, options is not an attribute,  that's why its here

2022-10-26 14:54 UTC, PAKovalev approved these changes

2022-10-26 15:04 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> +  const setPluginState = async (field: string, value: unknown) => {
it maps the setting state (synced with backend) to actuall api EP call
API calls should be done on the host (lines 47-55) and plugin would only call a simple setState function that does not know anything about API, just that you set some field to some value.

2022-10-26 15:05 UTC, Daboo1998 commented on packages/app/src/api/repositories/spaceRepository/spaceRepository.api.ts
> +import {RequestInterface} from '@momentum-xyz/core';
Why? it contains both options and metadata, why would you call both option?

2022-10-26 15:51 UTC, PAKovalev requested changes

2022-10-26 16:40 UTC, dmitry-yudakov requested changes
I think it's good generally, made a few remarks as the one regarding the setPluginSpace should be addressed.

2022-10-26 16:40 UTC, dmitry-yudakov commented on packages/app/src/scenes/collaboration/Collaboration.tsx
> +          );
perhaps `plugin` should contain `pluginState`? Or make spacePluginStateList an object, not array though I don't really see a point of hard separating the two of them?

2022-10-26 16:40 UTC, dmitry-yudakov commented on packages/app/src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> +  const setPluginState = async (field: string, value: unknown) => {
It's not completely wrong, it's just a simplifying wrapper function.

I'm wondering though if `pluginState` cannot have simple `setState(field, val)` function and have the rest of the arguments stored in it? We might need to call it from other places in Space screen, not only CollaborationPluginPage - for `plugin_chat` for example.

It's not a huge problem to stay this way for now but good to add `useCallback` probably?

2022-10-26 16:40 UTC, dmitry-yudakov commented on packages/app/src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> +  };
same here

2022-10-26 16:40 UTC, dmitry-yudakov commented on packages/sdk/src/interfaces/pluginProps.interface.ts
> +  setPluginState: <V>(key: string, value: V) => Promise<void>;
These could stay here for now but in the next version we'll probably have `sharedSpaceState` and `sharedWorldState` (or `sharedState`) - the space one would go to spacePluginProps interface then or now. 

I would also use the names that I mentioned, since they imply it's `shared`, because `plugin` state might be confusing.

2022-10-27 07:27 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> +  const setPluginState = async (field: string, value: unknown) => {
I cannot, cause otherwsie I cannot make it generic and type safe, at the same time

2022-10-27 07:37 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/Collaboration.tsx
> +          );
Yes I agree, I moved it

2022-10-27 07:41 UTC, Daboo1998 commented on packages/sdk/src/interfaces/pluginProps.interface.ts
> +  setPluginState: <V>(key: string, value: V) => Promise<void>;
good point, will rename to sharedState

2022-10-27 07:49 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> +  };
would have to drop type safety for this

2022-10-27 07:54 UTC, PAKovalev commented on packages/app/src/api/repositories/spaceRepository/spaceRepository.api.ts
> +import {RequestInterface} from '@momentum-xyz/core';
Because spaceRepo will have own interfaces, it is FE data. 
spaceOptionRepository is common reusable stuff.

2022-10-27 07:55 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> +  const setPluginState = async (field: string, value: unknown) => {
Guys, `ApiPluginInterface `.

2022-10-27 07:55 UTC, Daboo1998 commented on packages/app/src/api/repositories/spaceRepository/spaceRepository.api.ts
> +import {RequestInterface} from '@momentum-xyz/core';
What it is based on, I don't really know what you want spaceOptionRepository for? what is a space option? we don't have option but options and metadata

2022-10-27 07:56 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> +  };
Plugin should worry how to init ifself, not app.

2022-10-27 07:57 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx
> +  };
It does, we do not want to provide repositories though to the app...

2022-10-27 09:56 UTC, merged