Plugin SDK - Host Emulator - phase 2
momentum-xyz/ui-client pull request #380
Opened 2022-10-31 16:41 UTC by dmitry-yudakov

Planned development:
- move MomentumRequired to HostEmulator and show automatically when on PROD
- separate world and space interfaces
- widgets panel
- use react-router

2022-11-07 07:34 UTC, PAKovalev approved these changes

2022-11-07 07:34 UTC, PAKovalev commented on packages/sdk/src/emulator/components/WorldEmulator/WorldEmulator.tsx
> +            <button onClick={() => history.push(`/collaboration/${DUMMY_SPACE_ID}`)}>
Lets create routes as const.

2022-11-07 07:34 UTC, PAKovalev commented on packages/sdk/src/emulator/components/SpaceEmulator/SpaceEmulator.tsx
> +            <Route path={`${path}/dashboard`}>
Lets create routes as const.

2022-11-14 08:22 UTC, Daboo1998 requested changes

2022-11-14 08:22 UTC, Daboo1998 commented on packages/sdk/bin/momentum-plugin.js
> +    const command = script === 'start:plugin' ? 'start' : script;
instead of `start:plugin` I would make it a parameter you pass to something like `momentum-plugin start --no-craco` or `momentum-plugin start --standalone` or something else like that (maybe something shorter)

2022-11-14 08:22 UTC, Daboo1998 commented on packages/sdk/src/emulator/components/MomentumRequiredPage/MomentumRequiredPage.tsx
> -      <Text size="l" text={t('messages.momentumRequired')} weight="bold" />
Why removed translation?

2022-11-14 08:22 UTC, Daboo1998 commented on packages/sdk/src/emulator/components/SpaceEmulator/SpaceEmulator.tsx
> +  const [topBar = <span />, setTopBar] = useState<JSX.Element | null>(null);
why `<span />` not as initial value in `useState` call?

2022-11-14 17:00 UTC, dmitry-yudakov commented on packages/sdk/src/emulator/components/MomentumRequiredPage/MomentumRequiredPage.tsx
> -      <Text size="l" text={t('messages.momentumRequired')} weight="bold" />
To spare the need of having the translation file for SDK and make it simpler.

2022-11-15 07:52 UTC, dmitry-yudakov commented on packages/sdk/bin/momentum-plugin.js
> +    const command = script === 'start:plugin' ? 'start' : script;
It might mix with the underlying commands arguments - it's less ambiguous to use just just "command:specifier".
I also wanted the `start` command to work in standalone mode with hot refresh and so on - and `start:plugin` to be for the heavier and currently less functional version allowing to also plug it in local momentum.

2022-11-15 07:56 UTC, Daboo1998 commented on packages/sdk/bin/momentum-plugin.js
> +    const command = script === 'start:plugin' ? 'start' : script;
yes yes, I know I just don't like the `start:plugin` cause first of all we already have the word "plugin" in the script. I would suggest to look what arguments it can collide with and use a one that won't be colliding

2022-11-15 09:29 UTC, Daboo1998 approved these changes
I approve due to nature of the new setup

2022-11-15 09:40 UTC, merged