Feature/mir 17/BE EPs fixes
momentum-xyz/ui-client pull request #384
Opened 2022-11-01 16:26 UTC by Daboo1998

2022-11-01 17:59 UTC, dmitry-yudakov approved these changes

2022-11-01 17:59 UTC, dmitry-yudakov commented on packages/app/src/core/models/PluginAttributesManager/PluginAttributesManager.ts
> +      }
Maybe reuse the data for both requests? Or directly `yield self.setStateRequest.send( value === null ? delEP : setEP, {...body}`.
But it's ok to stay like this too.

2022-11-02 07:57 UTC, PAKovalev requested changes

2022-11-02 07:57 UTC, PAKovalev commented on packages/app/src/core/models/PluginAttributesManager/PluginAttributesManager.ts
> +      if (!response) {
one line:
`if (!response || !(key in response)) { 
   return null;
}`

2022-11-02 07:57 UTC, PAKovalev commented on packages/app/src/core/models/PluginAttributesManager/PluginAttributesManager.ts
> +          attribute_name: 'state',
Move to enum value of 'attribute_name'. See `api/enums`

2022-11-02 08:19 UTC, PAKovalev approved these changes

2022-11-02 08:21 UTC, merged