Feature/nex 2/magic link core function
momentum-xyz/ui-client pull request #390
Opened 2022-11-02 16:03 UTC by aminbksi

https://momentum.nifty.pm/l/zglzhSJvkl

Implement magic links as core FE app functionality

2022-11-02 16:36 UTC, Daboo1998 requested changes
Why does fetchMagicLink and generateMagicLink do the same biut one uses spaceId and second doesn't?

2022-11-02 16:36 UTC, Daboo1998 commented on packages/app/src/api/enums/attributeName.enum.ts
> +  MAGIC_LINK = 'magic_links',
`MAGIC_LINKS = 'magic_links'` or MAGIC_LINK = 'magic_link'

2022-11-02 16:36 UTC, Daboo1998 commented on packages/app/src/api/mapper/spaceAttribute.mapper.ts
> +};
What? Why? 1 file === 1 mapper

2022-11-02 16:36 UTC, Daboo1998 commented on packages/app/src/core/models/EventItem/EventItem.ts
> +        eventId: self.data?.id
I think its better to check spaceId and eventId before

2022-11-02 16:36 UTC, Daboo1998 commented on packages/app/src/core/models/EventItem/EventItem.ts
> +      return `${window.location.origin}/magic/${self.key}`;
maybe make a use of generatePath?

2022-11-02 16:36 UTC, Daboo1998 commented on packages/app/src/scenes/magic/pages/MagicPage/MagicPage.tsx
> +    magicStore.getMagicLink(id, worldStore.worldId);
maybe discuss with BE guys to not use worldId?

2022-11-02 16:36 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +        const key = uuidv4();
Why you don't use EventItem magic link

2022-11-02 17:26 UTC, dmitry-yudakov reviewed
It's a good first step from the existing architecture towards the new controller one.

It seems we have `api` as reusable piece of magic link logic used from many Stores but in future it'd better be common Store or Service, doing this - especially now when we generate uuid and do it in 3-4 places.

I'm not sure it will work since you seem to use space id for storing and world id for restoring the data, though it should be node id if I remember correctly :) 
I'm not why they need to be stored with node id and whether it isn't better to be world id, but anyway it should be consistent.

2022-11-03 08:57 UTC, aminbksi commented on packages/app/src/api/enums/attributeName.enum.ts
> +  MAGIC_LINK = 'magic_links',
I can ask BE to change it to `magic_link`, but as they said these all with one attrib. name, so it might be more concise if it will be `magic_links`

2022-11-03 08:58 UTC, aminbksi commented on packages/app/src/api/mapper/spaceAttribute.mapper.ts
> +};
I will make a separate file for it

2022-11-03 08:59 UTC, aminbksi commented on packages/app/src/scenes/magic/pages/MagicPage/MagicPage.tsx
> +    magicStore.getMagicLink(id, worldStore.worldId);
so if it will be `NODE_ID` there won't be needed to use `worldId`

2022-11-03 09:12 UTC, Daboo1998 commented on packages/app/src/api/enums/attributeName.enum.ts
> +  MAGIC_LINK = 'magic_links',
So use `MAGIC_LINKS = 'magic_links'`

2022-11-03 09:12 UTC, aminbksi commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +        const key = uuidv4();
we shouldn't have magic link in `EventItem` at all, we only generate it when we click on the open dialog, so I will get rid of it in `EventItem` model

2022-11-03 09:15 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +        const key = uuidv4();
but you still have fetchMagicLink in EventItem, why?

2022-11-03 09:16 UTC, aminbksi commented on packages/app/src/api/constants/app.variables.ts
> +  NODE_ID: ''
yes, we might want to use `NODE_ID` for setting and getting the attrib. for magic link

2022-11-03 09:16 UTC, aminbksi commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +        const key = uuidv4();
I am going to get rid of it. I'll remove it

2022-11-03 09:17 UTC, Daboo1998 commented on packages/app/src/scenes/magic/pages/MagicPage/MagicPage.tsx
> +    magicStore.getMagicLink(id, worldStore.worldId);
oh ok I forgot that now you need to use spaceAttributes for that. Ignore it

2022-11-03 11:11 UTC, PAKovalev requested changes

2022-11-03 11:11 UTC, PAKovalev commented on packages/app/src/api/mapper/spaceAttribute.mapper.ts
> +};
Amin, add pls some validation like object has keys for example.

2022-11-03 11:11 UTC, PAKovalev commented on packages/app/src/api/repositories/magicLinkRepository/magicLinkRepository.api.ts
> +import {AttributeNameEnum, PluginIdEnum} from '../../enums';
../

2022-11-03 11:11 UTC, PAKovalev commented on packages/app/src/api/repositories/magicLinkRepository/magicLinkRepository.api.ts
> +export const generateLink: RequestInterface<MagicLinkGenerateRequest, SpaceSubAttributeResponse> = (
`createLink` will be better to avoid confusion.

2022-11-03 11:11 UTC, PAKovalev commented on packages/app/src/core/models/EventItem/EventItem.ts
> +        eventId: self.data?.id
Btw: not good to create magic when we load event. But it will be improved later.

2022-11-03 11:11 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +        const key = uuidv4();
`const key: string = uuidv4();`

2022-11-03 11:11 UTC, PAKovalev commented on packages/app/src/scenes/magic/pages/MagicPage/MagicPage.tsx
> +    const spaceId = magicStore.magic.spaceId;
Maybe `magicStore.magicLink.spaceId` will better. I know it is old code.

2022-11-03 11:11 UTC, PAKovalev commented on packages/app/src/scenes/widgets/pages/MagicLinkWidget/MagicLinkWidget.tsx
> +  const {generate, address, request} = magicLink;
Don't use `request` in components. Make a `view`.

2022-11-03 11:11 UTC, PAKovalev commented on packages/app/src/scenes/widgets/stores/MagicLinkStore/models/MagicLink/MagicLink.ts
> +      return `${document.location.origin}/magic/${self.key}`;
`generatePath`

2022-11-03 13:37 UTC, Daboo1998 requested changes
This whole key thing is confusing and does not make sense, the rest is a good improvment

2022-11-03 13:37 UTC, Daboo1998 commented on packages/app/src/core/models/EventItem/EventItem.ts
> +    key: ''
what's that? and where is it set?

2022-11-03 13:37 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +        key: 'current-position',
Why? Make an enum and use that instead

2022-11-03 13:37 UTC, Daboo1998 commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +          self.key = uuidv4();
does not make sense, first its "current-position" and now you set it uuid

2022-11-03 13:38 UTC, PAKovalev requested changes

2022-11-03 13:38 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +          const response = yield self.magicLinkRequest.send(api.magicLinkRepository.createLink, {
btw: do we create link when we show dialog? or after pressing `copy to clipboard`?

2022-11-03 13:38 UTC, PAKovalev commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +      return `${window.location.protocol}//${window.location.host}${generatePath(ROUTES.magic, {
`window.locatio.origin`

2022-11-03 13:38 UTC, PAKovalev commented on packages/app/src/scenes/widgets/pages/MagicLinkWidget/MagicLinkWidget.tsx
> +  const {generate, address, request, wasCreated} = magicLink;
why `request`? )

2022-11-03 13:51 UTC, aminbksi commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +          const response = yield self.magicLinkRequest.send(api.magicLinkRepository.createLink, {
I think it's being done in the dialog not in store, I couldn't check this part since we don't have calendar EP working, only in widget, it's being generated once we click copy to clipboard, I'll fix the functionality once we have calendar api working

2022-11-03 13:54 UTC, aminbksi commented on packages/app/src/core/models/EventItem/EventItem.ts
> +    key: ''
it's the uuid we're generating as a key

2022-11-03 13:55 UTC, aminbksi commented on packages/app/src/scenes/collaboration/stores/CalendarStore/CalendarStore.ts
> +        key: 'current-position',
it is for sake of user experience, to avoid showing, null, undefined, in url in the dialog

2022-11-03 14:36 UTC, PAKovalev approved these changes

2022-11-03 15:25 UTC, aminbksi commented on packages/app/src/api/repositories/magicLinkRepository/magicLinkRepository.api.ts
> +    value: {data},
we should think about how to create a json schema maybe in FE, since there is no structure in BE for storing them, I agree with you here

2022-11-03 15:26 UTC, Daboo1998 requested changes

2022-11-03 15:26 UTC, Daboo1998 commented on packages/app/src/core/models/EventItem/EventItem.ts
>      })
It does not fetch anything right now, doesn't it 😉

2022-11-03 15:26 UTC, Daboo1998 commented on packages/app/src/scenes/magic/stores/MagicStore/MagicStore.ts
>      })
This fetches though, so I would not call it getMagicLink but fetchMagicLink

2022-11-03 15:26 UTC, Daboo1998 commented on packages/app/src/scenes/widgets/stores/MagicLinkStore/models/MagicLink/MagicLink.ts
> +    generate: flow(function* (type: MagicTypeEnum, spaceId?: string, position?: any) {
maybe generateAndCopyToClipboard ?

2022-11-03 15:27 UTC, Daboo1998 approved these changes
I approve, but pls make the cosmetic changes

2022-11-03 15:29 UTC, aminbksi commented on packages/app/src/scenes/widgets/stores/MagicLinkStore/models/MagicLink/MagicLink.ts
> +    generate: flow(function* (type: MagicTypeEnum, spaceId?: string, position?: any) {
isn't too long?

2022-11-03 15:32 UTC, aminbksi commented on packages/app/src/scenes/widgets/stores/MagicLinkStore/models/MagicLink/MagicLink.ts
> +    generate: flow(function* (type: MagicTypeEnum, spaceId?: string, position?: any) {
`copyToClipBoard` I would say

2022-11-03 15:39 UTC, dmitry-yudakov approved these changes

2022-11-03 15:43 UTC, Daboo1998 commented on packages/app/src/scenes/widgets/stores/MagicLinkStore/models/MagicLink/MagicLink.ts
> +    generate: flow(function* (type: MagicTypeEnum, spaceId?: string, position?: any) {
ok I'm fine with that

2022-11-03 15:50 UTC, merged