Feature/mir 64/load config from be
momentum-xyz/ui-client pull request #395
Opened 2022-11-03 12:26 UTC by Daboo1998

2022-11-03 14:22 UTC, PAKovalev requested changes

2022-11-03 14:22 UTC, PAKovalev commented on packages/app/src/core/models/PluginAttributesManager/PluginAttributesManager.ts
>      get: flow(function* <T>(spaceId: string, key: string) {
Btw: maybe `getState` will be better?

2022-11-03 14:22 UTC, PAKovalev commented on packages/plugin_miro/src/SpaceApp.tsx
> +    props.api.getConfig().then((config) => {
It should be a part of store like:

`useEffect(() => {
 miroStore.init(api);
})`

2022-11-03 14:57 UTC, dmitry-yudakov approved these changes

2022-11-03 16:28 UTC, Daboo1998 commented on packages/app/src/core/models/PluginAttributesManager/PluginAttributesManager.ts
>      get: flow(function* <T>(spaceId: string, key: string) {
I don't think so cause its not about getting state, but a particular value from it

2022-11-03 19:16 UTC, dmitry-yudakov approved these changes

2022-11-03 19:16 UTC, dmitry-yudakov commented on packages/plugin_miro/src/stores/RootMiroStore.ts
> +        appVariables[key as keyof AppConfigInterface] = value as string;
It would be better to use the type of your actual config somehow without type assertion with `as`. You know what you expect, you use typescript generics in `api` but you don't really benefit from it.

It's not critical of course, just an observation.

2022-11-03 19:16 UTC, dmitry-yudakov commented on packages/sdk/src/emulator/HostEmulator.tsx
> +interface PropsInterface<C extends PluginConfigInterface> {
Perhaps initializing type with default value like `<C extends PluginConfigInterface = PluginConfigInterface>` would work - to simplify using it later.

2022-11-03 19:16 UTC, dmitry-yudakov commented on packages/app/src/core/models/PluginAttributesManager/PluginAttributesManager.ts
> +          spaceId: appVariables.NODE_ID,
I'm not really sure why NODE_ID needs to be used for config, perhaps it's a temp thing if getting inherited space config is not available.

2022-11-04 08:08 UTC, Daboo1998 commented on packages/plugin_miro/src/stores/RootMiroStore.ts
> +        appVariables[key as keyof AppConfigInterface] = value as string;
ah yes forgot about that :)

2022-11-04 08:11 UTC, Daboo1998 commented on packages/app/src/core/models/PluginAttributesManager/PluginAttributesManager.ts
> +          spaceId: appVariables.NODE_ID,
for now in plan is to use node config for plugins that is shared through the app. For example for Miro its MIRO_APP_ID and it should not differ. In future we can make two calls, one for node and one for config overrides for space, but that's maybe in the future

2022-11-04 08:34 UTC, Daboo1998 commented on packages/sdk/src/emulator/HostEmulator.tsx
> +interface PropsInterface<C extends PluginConfigInterface> {
Good idea

2022-11-04 08:41 UTC, dmitry-yudakov approved these changes

2022-11-04 08:47 UTC, merged