Create an adding/removing plugins interface
momentum-xyz/ui-client pull request #399
Opened 2022-11-04 15:20 UTC by Daboo1998

2022-11-04 16:08 UTC, dmitry-yudakov approved these changes

2022-11-07 07:21 UTC, PAKovalev requested changes

2022-11-07 07:21 UTC, PAKovalev commented on packages/app/src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/AddPluginDialog/AddPluginDialog.tsx
> +import {t} from 'i18next';
Hook instead of object

2022-11-07 07:21 UTC, PAKovalev commented on packages/app/src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/AddPluginDialog/AddPluginDialog.tsx
> +      pluginsStore.setQuery('');
Make or use reset function from store

2022-11-07 07:21 UTC, PAKovalev commented on packages/app/src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/AddPluginDialog/AddPluginDialog.tsx
> +      title="Add plugin"
i18n

2022-11-07 07:21 UTC, PAKovalev commented on packages/app/src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/AddPluginDialog/AddPluginDialog.tsx
> +          label="Search"
i18n

2022-11-07 07:21 UTC, PAKovalev commented on packages/app/src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/AddPluginDialog/AddPluginDialog.tsx
> +            placeholder="Select Plugin"
i18n

2022-11-07 07:21 UTC, PAKovalev commented on packages/app/src/stores/MainStore/models/PluginsStore/PluginsStore.ts
> +const PluginQueryResult = types.model('PluginQueryResult', {
1 file === 1 model

2022-11-07 07:21 UTC, PAKovalev commented on packages/app/src/stores/MainStore/models/PluginsStore/PluginsStore.ts
> +    setQuery(query: string) {
There is common `SearchQuery` model

2022-11-07 07:21 UTC, PAKovalev commented on packages/app/src/stores/MainStore/models/PluginsStore/PluginsStore.ts
> +    searchPlugins: flow(function* () {
If we expect that search will be implemented on BE side, add TODO comment.
If not, make a view `filteredPlugins`, no need to call the same be endpoint all the time.

2022-11-07 07:59 UTC, Daboo1998 commented on packages/app/src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/AddPluginDialog/AddPluginDialog.tsx
> +      pluginsStore.setQuery('');
I cannot reset the whole model, cause there some stuff that should not be reset

2022-11-07 08:17 UTC, Daboo1998 commented on packages/app/src/scenes/spaceAdmin/pages/SpaceAdminPage/components/organisms/AddPluginDialog/AddPluginDialog.tsx
> +      pluginsStore.setQuery('');
Ok after using SearchQuery it will be possible

2022-11-07 08:20 UTC, Daboo1998 commented on packages/app/src/stores/MainStore/models/PluginsStore/PluginsStore.ts
> +    searchPlugins: flow(function* () {
Asked BE guys to add queries to the EP, depending on wether it will be possible or not, will move it to views or leave here. Leaving a TODO for now

2022-11-07 08:35 UTC, PAKovalev approved these changes

2022-11-07 08:38 UTC, merged