API exponential retry of HTTP error 503 before redirect to Maintenance page
momentum-xyz/ui-client pull request #400
Opened 2022-11-04 17:44 UTC by dmitry-yudakov

Currently we redirect to maintenance page when a single error 503 is received - better retry it several times before failing it.

Needs to be tested more - combination of another interceptors for axios error that we set.

2022-11-11 12:10 UTC, PAKovalev commented on packages/app/src/scenes/App.tsx
> +    setAxiosRetry({
Lets create a hook instead of useEffect

2022-11-12 08:53 UTC, PAKovalev approved these changes

2022-11-12 08:53 UTC, PAKovalev commented on packages/app/src/api/request/request.ts
> +  retryCodes = [503]
Use existing constants.

2022-11-12 08:53 UTC, PAKovalev commented on packages/app/src/api/request/request.ts
> +  maxRetries = 3,
Let's move this to the env file.

2022-11-12 08:53 UTC, PAKovalev commented on packages/app/src/scenes/App.tsx
>    useEffect(() => {
Lets create a hook under `shared/hooks`.

2022-11-14 08:39 UTC, Daboo1998 requested changes

2022-11-14 08:39 UTC, Daboo1998 commented on packages/app/src/api/request/request.ts
> +  return Promise.reject(error) as unknown;
why not change to async and then throw error?

2022-11-14 08:39 UTC, Daboo1998 commented on packages/app/src/stores/ConfigStore/ConfigStore.ts
> +          appVariables[key as keyof AppConfigInterface] = value as string;
actually this is wrong. It should be 
```suggestion
          appVariables[key as keyof AppConfigExtendedInterface] = value as any;
```

as appVariables are of type `AppConfigExtendedInterface`

2022-11-14 17:40 UTC, dmitry-yudakov commented on packages/app/src/stores/ConfigStore/ConfigStore.ts
> +          appVariables[key as keyof AppConfigInterface] = value as string;
It doesn't really matter - it's just casting of stuff and doesn't affect anything. And `any` will give us warning.

2022-11-15 07:21 UTC, dmitry-yudakov commented on packages/app/src/scenes/App.tsx
>    useEffect(() => {
I'll leave it as is for the moment. Lets discuss when you're back. I don't think it's good to hide all the logic of this effect in a hook, yet if it's just to spare useEffect+setApiResponseHandlers it's meaningless and only gives you pain of setting up the types and figuring out how to solve the issue of the inner deps list of the same useEffect.

2022-11-15 07:38 UTC, dmitry-yudakov commented on packages/app/src/stores/ConfigStore/ConfigStore.ts
> +          appVariables[key as keyof AppConfigInterface] = value as string;
And it gives error `Type 'any' is not assignable to type 'never'.` if AppConfigExtendedInterface is used, whatever the hell it means. Lets just leave it as is ;)

2022-11-15 07:39 UTC, dmitry-yudakov commented on packages/app/src/api/request/request.ts
> +  return Promise.reject(error) as unknown;
It was needed for the first implementation, but now I just restored it to the original `throw error`.

2022-11-15 07:40 UTC, dmitry-yudakov commented on packages/app/src/api/request/request.ts
> +  maxRetries = 3,
Similar parameters like response timeout are in this file, so I put the new ones next to them.

2022-11-15 10:01 UTC, Daboo1998 approved these changes

2022-11-15 10:13 UTC, merged