Feature/space calendar
momentum-xyz/ui-client pull request #423
Opened 2022-11-16 17:36 UTC by aminbksi

2022-11-21 15:39 UTC, PAKovalev requested changes

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/core/models/EventItem/models/AttendeesList/AtendeesList.ts
> +      attendees: types.array(types.frozen<UserModelInterface>()),
Use model instead of interface

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/core/models/EventItem/models/AttendeesList/AtendeesList.ts
> +      searchedAttendees: types.maybe(types.array(types.frozen<UserModelInterface>())),
Use model instead of interface

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/core/models/EventItem/models/AttendeesList/AtendeesList.ts
> +      searchAttendees(query: string) {
return type

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/scenes/App.routes.tsx
> +const Calendar = lazy(() => import('./calendar/Calendar'));
CalendarPage

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/scenes/calendar/Calendar.tsx
> +import React from 'react';
Remove this file.

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/scenes/calendar/stores/CalendarStore.ts
> +        console.info(event);
remove

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/scenes/calendar/stores/OdysseyCalendarStore/OdysseyCalendarStore.ts
> +const OdysseyCalendarStore = types.compose(
`CalendarStore`

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/shared/services/i18n/locales/en-gb.ts
> +      joinGathering: 'Gathering EventItem is starting now',
Are you sure?)

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/ui-kit/organisms/EventItem/components/templates/EventInformation/EventInformation.tsx
> +              text="More Attendees"
i18n

2022-11-21 15:39 UTC, PAKovalev commented on packages/app/src/ui-kit/organisms/EventItem/components/templates/EventInformation/EventInformation.tsx
> +                text={`+${event.attendeesList.attendees.length - 4}`}
Move to store as view

2022-11-21 16:11 UTC, dmitry-yudakov approved these changes

2022-11-21 16:11 UTC, dmitry-yudakov commented on packages/app/src/core/models/EventForm/EventForm.ts
> +      createEventAttribute: flow(function* (
I think `createEvent` was a better name here - the fact that it's an attribute is a low level detail.

2022-11-21 16:11 UTC, dmitry-yudakov commented on packages/app/src/core/models/EventItem/EventItem.ts
> +    withdrawAttending: flow(function* (spaceId: string, eventId: string, userId: string) {
`attend` and `withdrawAttending` are very similar - I think it's worth having a private `_updateAttendies` function here, accepting same parameters and flag isAttending - depending on this you either add or delete userId from attendees object. `attend` and `withdraw` would simply call `_updateAttendies` with different values of `isAttending` flag.

2022-11-21 16:11 UTC, dmitry-yudakov commented on packages/app/src/ui-kit/organisms/EventItem/components/templates/EventActions/EventActions.tsx
> +import {observer} from 'mobx-react-lite';
is `ui-kit` supposed to use `MST`? probably not

2022-11-21 16:11 UTC, dmitry-yudakov commented on packages/app/src/ui-kit/organisms/EventItem/components/templates/EventInformation/EventInformation.tsx
> +import {observer} from 'mobx-react-lite';
without MST?

2022-11-21 16:15 UTC, aminbksi commented on packages/app/src/ui-kit/organisms/EventItem/components/templates/EventActions/EventActions.tsx
> +import {observer} from 'mobx-react-lite';
it's in app, not `ui-kit` package, and it's not using mst, it is for just being observable, we already have it for the component we kept in `app/ui-kit` (some of them though)

2022-11-21 16:18 UTC, dmitry-yudakov commented on packages/app/src/ui-kit/organisms/EventItem/components/templates/EventActions/EventActions.tsx
> +import {observer} from 'mobx-react-lite';
my bad

2022-11-21 16:18 UTC, aminbksi commented on packages/app/src/core/models/EventItem/EventItem.ts
> +    withdrawAttending: flow(function* (spaceId: string, eventId: string, userId: string) {
I am not sure if it's a better idea to not to have separate functions for both of them, since they are already long functions, advice please @PAKovalev

2022-11-22 07:36 UTC, PAKovalev requested changes

2022-11-22 07:36 UTC, PAKovalev commented on packages/app/src/api/repositories_OLD/old_eventsRepository/old_eventsRepository.api.ts
> +import {eventsRepositoryEndpoints} from './old_eventsRepository.api.endpoints';
Can we remove old repo?

2022-11-22 07:36 UTC, PAKovalev commented on packages/app/src/core/models/EventForm/EventForm.ts
> +      createEvent: flow(function* (
createOrUpdateEvent? It seems like two functions quite similar.

2022-11-22 07:36 UTC, PAKovalev commented on packages/app/src/core/models/EventForm/EventForm.ts
> +      updateEventAttribute: flow(function* (
Make 1 function for creating and updating.

2022-11-22 07:36 UTC, PAKovalev commented on packages/app/src/scenes/calendar/pages/CalendarPage/CalendarPage.tsx
> +    // @ts-ignore
Just remove.

2022-11-22 07:36 UTC, PAKovalev commented on packages/app/src/scenes/calendar/pages/CalendarPage/CalendarPage.tsx
> +          subtitle="Calendar"
i18n

2022-11-22 08:52 UTC, PAKovalev approved these changes

2022-11-22 09:29 UTC, merged