Feature/implement voice chat
momentum-xyz/ui-client pull request #452
Opened 2022-11-30 14:29 UTC by Daboo1998

2022-11-30 15:12 UTC, PAKovalev requested changes

2022-11-30 15:12 UTC, PAKovalev commented on packages/app/src/scenes/home/pages/HomePage/components/templates/SocialPanel/SocialPanel.tsx
> +const SocialPanel: FC = () => {
It is widget!

2022-11-30 15:12 UTC, PAKovalev commented on packages/app/src/scenes/App.routes.tsx
> -  {
revert back.

2022-11-30 15:12 UTC, PAKovalev commented on packages/app/src/scenes/App.tsx
> +                <HomePage />
Remove!

2022-11-30 16:51 UTC, dmitry-yudakov approved these changes

2022-11-30 16:51 UTC, dmitry-yudakov commented on packages/app/src/scenes/home/pages/HomePage/HomePage.tsx
> +  }
Is this actually needed?

2022-11-30 16:51 UTC, dmitry-yudakov commented on packages/app/src/scenes/widgets/pages/SocialWidget/SocialWidget.tsx
> +  const selectedTab = useMemo(() => tabs[selectedTabIndex], [selectedTabIndex, tabs]);
no need of memo here

2022-11-30 17:07 UTC, PAKovalev approved these changes

2022-12-01 08:12 UTC, Daboo1998 commented on packages/app/src/scenes/home/pages/HomePage/HomePage.tsx
> +  }
Now not

2022-12-01 08:36 UTC, merged