feature(app): agora screen share
momentum-xyz/ui-client pull request #455
Opened 2022-11-30 18:23 UTC by aminbksi

2022-11-30 19:13 UTC, PAKovalev requested changes

2022-11-30 19:13 UTC, PAKovalev commented on packages/app/src/stores/AgoraStore/AgoraMeetingStore/AgoraMeetingStore.ts
> +        api.agoraRepository_old.getAgoraToken,
why do we use old store?

2022-12-01 07:17 UTC, aminbksi commented on packages/app/src/stores/AgoraStore/AgoraMeetingStore/AgoraMeetingStore.ts
> +        api.agoraRepository_old.getAgoraToken,
this is related to `meeting` as I changed the response of token, the new one doesn't match, so it needs to be changed, but Daniel is working on that as far as I know

2022-12-01 07:48 UTC, PAKovalev approved these changes

2022-12-01 08:51 UTC, Daboo1998 requested changes

2022-12-01 08:51 UTC, Daboo1998 commented on packages/app/src/scenes/widgets/stores/ScreenShareStore/ScreenShareStore.ts
>          });
Add a TODO or implement the new EP. 

The new EP is `api/v4/users/:userId`

2022-12-01 08:51 UTC, Daboo1998 commented on packages/app/src/scenes/widgets/stores/ScreenShareStore/ScreenShareStore.ts
> +      world: types.maybeNull(Space),
Do you really need the whole world for that? Just use worldId. Also you can get it from worldStore, no need to use a new request

2022-12-01 08:51 UTC, Daboo1998 commented on packages/app/src/scenes/widgets/stores/ScreenShareStore/ScreenShareStore.ts
> +      fetchWorld: flow(function* (spaceId: string) {
Do you really need this? Why not get it from worldStore? (Look at my PR for example, I just pass worldId as argument to init or join)

2022-12-01 08:51 UTC, Daboo1998 commented on packages/app/src/stores/AgoraStore/AgoraMeetingStore/AgoraMeetingStore.ts
> +        api.agoraRepository_old.getAgoraToken,
You can now use the new repo after fixing conflicts :)

2022-12-01 08:51 UTC, Daboo1998 commented on packages/app/src/stores/AgoraStore/AgoraScreenShareStore/AgoraScreenShareStore.ts
> +      self.client.leave();
you may want to close local and remote track just in case

2022-12-01 08:51 UTC, Daboo1998 commented on packages/app/src/stores/MainStore/models/AgoraStore/AgoraMeetingStore/AgoraMeetingStore.ts
> +        api.agoraRepository_old.getAgoraToken,
use new repo now

2022-12-01 08:51 UTC, Daboo1998 commented on packages/app/src/stores/MainStore/models/AgoraStore/AgoraStageModeStore/AgoraStageModeStore.ts
> +        api.agoraRepository_old.getAgoraToken,
Use new repo now

2022-12-01 08:51 UTC, Daboo1998 commented on packages/app/src/stores/AgoraStore/AgoraScreenShareStore/AgoraScreenShareStore.ts
> +      self.client.leave();
Or just do 
```
self.client?.localTracks.forEach((track) => {
     track.close();
});
```

2022-12-01 08:51 UTC, Daboo1998 commented on packages/app/src/stores/AgoraStore/AgoraScreenShareStore/AgoraScreenShareStore.ts
> +      self.client.leave();
Unless you sure that its works without that

2022-12-01 09:31 UTC, aminbksi commented on packages/app/src/stores/AgoraStore/AgoraScreenShareStore/AgoraScreenShareStore.ts
> +      self.client.leave();
it's working now, so I'll keep it as it is

2022-12-01 09:55 UTC, Daboo1998 approved these changes

2022-12-01 09:55 UTC, Daboo1998 commented on packages/app/src/scenes/widgets/stores/ScreenShareStore/ScreenShareStore.ts
> +        // TODO: when implemented the user repository fetchProfile
What to do when that happens? pls add that

2022-12-01 10:22 UTC, merged