Feat/nft info panel
momentum-xyz/ui-client pull request #541
Opened 2022-12-13 15:27 UTC by FIZLIN

2022-12-14 10:36 UTC, dmitry-yudakov approved these changes

2022-12-14 16:59 UTC, dmitry-yudakov approved these changes
It seems ok in general but I think in `OdysseyInfo` the image should be taken directly from `odyssey` and we should use some placeholder image if it's missing.

2022-12-14 16:59 UTC, dmitry-yudakov commented on packages/app/src/scenes/explore/pages/ExplorePage/components/organisms/SelectedOdyssey/SelectedOdyssey.tsx
> +        avatar={odyssey.image}
Do we need the `avatar` property here? It can take `odyssey.image` internally.

2022-12-19 10:17 UTC, PAKovalev requested changes

2022-12-19 10:17 UTC, PAKovalev commented on packages/app/src/scenes/explore/pages/ExplorePage/components/organisms/SelectedOdyssey/SelectedOdyssey.tsx
> +        avatar={odyssey.image}
Agree, remove avatar prop pls.

2022-12-19 10:17 UTC, PAKovalev commented on packages/app/src/ui-kit/molecules/OdysseyInfo/OdysseyInfo.styled.ts
> +  color: #fff2f1;
Move this color to `variables.css`.

2022-12-19 10:17 UTC, PAKovalev commented on packages/app/src/ui-kit/molecules/OdysseyInfo/OdysseyInfo.tsx
> +            src={getImageAbsoluteUrl(avatar) || ''}
`getImageAbsoluteUrl(odyssey.image) || ''`

2022-12-19 10:17 UTC, PAKovalev commented on packages/app/src/ui-kit/molecules/OdysseyInfo/OdysseyInfo.tsx
> +          <styled.StatisticsValue>{odyssey.connections} connections</styled.StatisticsValue>
i18n

2022-12-19 10:17 UTC, PAKovalev commented on packages/app/src/ui-kit/molecules/OdysseyInfo/OdysseyInfo.tsx
> +          <styled.StatisticsValue>{odyssey.docking} docking</styled.StatisticsValue>
i18n

2022-12-19 10:17 UTC, PAKovalev commented on packages/app/src/ui-kit/molecules/OdysseyInfo/OdysseyInfo.tsx
> +          <styled.StatisticsValue>{odyssey.events} events</styled.StatisticsValue>
i18n

2022-12-19 10:17 UTC, PAKovalev commented on packages/ui-kit/src/molecules/Image/Image.tsx
> +  className?: string;
Remove className prop. It breaks styled-components overriding.

2022-12-19 13:41 UTC, PAKovalev approved these changes

2022-12-19 13:42 UTC, merged