feat(get-tokens): Added button + wait 24hrs logic;
momentum-xyz/ui-client pull request #546
Opened 2022-12-15 13:44 UTC by FIZLIN

2022-12-19 11:25 UTC, dmitry-yudakov requested changes
Lets create `blockchain.utils` under `core` package - with functions `saveLastAirdropInfo`, `canRequestAirdrop` or perhaps even better `getTimeToNextAllowedAirdrop`. 

Inability to ask for airdrop could be with error or disabled button and small info text explaining why and when it will be available.

2022-12-19 11:25 UTC, dmitry-yudakov commented on packages/app/src/core/constants/lastAirdrop.constants.ts
> +export const LAST_AIRDROP_KEY = 'last_airdrop';
I think this file is better be `blockchain.constants` and we could later put more things in it.

2022-12-20 07:48 UTC, PAKovalev requested changes

2022-12-20 07:48 UTC, PAKovalev commented on packages/app/src/scenes/explore/pages/ExplorePage/components/organisms/StakingDashboard/StakingDashboard.tsx
> +  canRequestAirdrop as canRequestAirdropFn,
Don't rename functions. Use name as is or rename.

2022-12-20 07:48 UTC, PAKovalev commented on packages/app/src/scenes/explore/pages/ExplorePage/components/organisms/StakingDashboard/StakingDashboard.tsx
> +  const [canRequestAirdrop, setCanRequestAirdrop] = useState(canRequestAirdropFn());
useState<boolean>

2022-12-20 19:24 UTC, dmitry-yudakov approved these changes
It's pretty good overall and could be merged IMO. Shared few hints for improvement.

2022-12-20 19:24 UTC, dmitry-yudakov commented on packages/core/src/utils/blockchain.utils.ts
> +  const timeToNextAllowedAirdrop = lastAirdropTimestamp + AIRDROP_TIMEOUT_MS - now;
it would be easier to return 0 if allowed instead of negative value

2022-12-20 19:24 UTC, dmitry-yudakov commented on packages/core/src/utils/blockchain.utils.ts
> +  const airdropAvailableDate = new Date(lastAirdropTimestamp + AIRDROP_TIMEOUT_MS);
I'd say use `getTimeToNextAllowedAirdrop` with just applying the formatting on it.

2022-12-20 19:24 UTC, dmitry-yudakov commented on packages/core/src/utils/blockchain.utils.ts
> +  const airdropAvailableDate = new Date(lastAirdropTimestamp + AIRDROP_TIMEOUT_MS);
I see we're using `date-fns` in some components - perhaps we could use it for the formatting where it's needed and return just a Date from here. Perhaps @PAKovalev will have good advice here.

2022-12-21 08:03 UTC, PAKovalev approved these changes

2022-12-21 15:14 UTC, merged