Implemented #1785
momentum-xyz/ui-client pull request #55
Opened 2022-05-30 12:31 UTC by Daboo1998

2022-05-30 14:11 UTC, PAKovalev requested changes

2022-05-30 14:11 UTC, PAKovalev commented on src/ui-kit/atoms/Button/Button.styled.ts
> +  &.withBackground {
Make a new variant instead of this property

2022-05-30 14:11 UTC, PAKovalev commented on src/ui-kit/atoms/Button/Button.tsx
> +interface PropsInterface
Just add non-required prop `className` in PropsWithThemeInterface.

2022-05-30 14:43 UTC, PAKovalev approved these changes

2022-05-31 05:15 UTC, gerbenrobijn-sigbar approved these changes

2022-05-31 07:53 UTC, merged