Feature/#1564 add person turning on stage mode to stage
momentum-xyz/ui-client pull request #57
Opened 2022-05-31 09:57 UTC by gerbenrobijn-sigbar

2022-05-31 09:58 UTC, PAKovalev approved these changes

2022-05-31 14:54 UTC, Daboo1998 requested changes

2022-05-31 14:54 UTC, Daboo1998 commented on src/component/layout/StageMode/StageModeControlPanelLayout.tsx
> +      if (userToggledStageOn) {
combine it into one if statement

2022-05-31 14:54 UTC, Daboo1998 commented on src/component/molucules/collaboration/RemoteParticipantView.tsx
> +    // console.info(`Agora remote participant user updated for ${userName}`, participant);
Just I would say remove it

2022-06-01 08:45 UTC, PAKovalev approved these changes

2022-06-02 07:02 UTC, Daboo1998 approved these changes

2022-06-02 07:10 UTC, merged