Feat/online users list
momentum-xyz/ui-client pull request #595
Opened 2023-01-12 15:16 UTC by FIZLIN

2023-01-12 15:38 UTC, dmitry-yudakov approved these changes

2023-01-13 08:18 UTC, PAKovalev requested changes

2023-01-13 08:18 UTC, PAKovalev commented on packages/app/src/scenes/widgets/pages/SearchUsersWidget/SearchUsersWidget.tsx
> +  const listedUsers =
Make a view under onlineUsersStore model.

2023-01-13 08:32 UTC, FIZLIN commented on packages/app/src/scenes/widgets/pages/SearchUsersWidget/SearchUsersWidget.tsx
> +  const listedUsers =
✅

2023-01-13 10:01 UTC, PAKovalev approved these changes

2023-01-13 10:03 UTC, merged