Plugin SDK improvements and simplification, twitch/vimeo plugins
momentum-xyz/ui-client pull request #600
Opened 2023-01-13 18:25 UTC by dmitry-yudakov

2023-01-31 08:15 UTC, PAKovalev requested changes

2023-01-31 08:15 UTC, PAKovalev commented on packages/sdk/src/utils/UnityAutoPause.tsx
> +export const AutoPauseUnity: FC = () => {
It is a hook. I should be named `useAutoPauseUnity`. Move to hooks also.

2023-01-31 08:15 UTC, PAKovalev commented on packages/sdk/src/utils/UnityAutoTakeKeyboardControl.tsx
> +export const UnityAutoTakeKeyboardControl: FC = () => {
It is a hook. I should be named `useUnityAutoTakeKeyboardControl`. Move to hooks also.

2023-01-31 08:15 UTC, PAKovalev commented on packages/app/src/scenes/object/pages/ObjectPluginPage/ObjectPluginPage.tsx
> +const PluginInnerWrapper = ({
Make a component under a `ObjectPluginPage`. One file === One component.

2023-01-31 08:15 UTC, PAKovalev commented on packages/plugin_vimeo/src/Plugin.tsx
> +const usePlugin: UsePluginHookType = (props) => {
Why do we have 2 plugins? One is for vimeo and second one for twitch?  These plugins are familiar. Secondly, we don't have plugin for youtube. My opinion, we should have only one plugin named `VideoViewer` (or something like this) which will be used for youtube, vimeo, twitch, etc. In order to support an additional video service - we just need to adapt existing plugin, we don't want to create and deploy a new one.

2023-01-31 08:15 UTC, PAKovalev commented on packages/plugin_vimeo/src/Plugin.tsx
> +        label="Channel"
i18n

2023-01-31 08:15 UTC, PAKovalev commented on packages/plugin_vimeo/src/Plugin.tsx
> +      <Text text="Video not yet set" size="m" />
i18n

2023-01-31 08:15 UTC, PAKovalev commented on packages/sdk/src/contexts/SpaceGlobalPropsContext.tsx
> +export const ObjectGlobalPropsContext = createContext<PluginPropsInterface>({
Take a look on file name. )

2023-01-31 08:37 UTC, dmitry-yudakov commented on packages/app/src/scenes/object/pages/ObjectPluginPage/ObjectPluginPage.tsx
> +const PluginInnerWrapper = ({
It's more flexible this way, because you could put `< AutoPauseUnity/>` into conditionally rendered piece of code - not whole component. This way some video plugin may work while you're flying around in unity, but if you open edit form for changing video, it will take keyboard control.

2023-01-31 17:16 UTC, dmitry-yudakov commented on packages/sdk/src/utils/UnityAutoTakeKeyboardControl.tsx
> +export const UnityAutoTakeKeyboardControl: FC = () => {
It's more flexible this way, because you could put `<UnityAutoTakeKeyboardControl/>` into conditionally rendered piece of code - not whole component. This way some video plugin may work while you're flying around in unity, but if you open edit form for changing video, it will take keyboard control.

2023-01-31 17:21 UTC, dmitry-yudakov commented on packages/app/src/scenes/object/pages/ObjectPluginPage/ObjectPluginPage.tsx
> +const PluginInnerWrapper = ({
Well, these aren't really 2 independent components - the second is more of an implementation detail required by the fact that I call a hook, requiring Context and I couldn't find a way to mix those in one component - and that's how we got 2 components but they're part of one logic and better stay together.

2023-02-01 08:36 UTC, dmitry-yudakov commented on packages/plugin_vimeo/src/Plugin.tsx
> +const usePlugin: UsePluginHookType = (props) => {
yeah, it's a good idea

2023-02-03 12:49 UTC, merged