Feat/react 18
momentum-xyz/ui-client pull request #603
Opened 2023-01-19 12:58 UTC by FIZLIN

2023-01-26 09:37 UTC, PAKovalev requested changes

2023-01-26 09:37 UTC, PAKovalev commented on packages/app/src/scenes/App.tsx
> +  // // PUBLIC ROUTES
Why is it commented?

2023-01-26 13:06 UTC, FIZLIN commented on packages/app/src/scenes/App.tsx
> +  // // PUBLIC ROUTES
Can up when rebasing the onboarding changes. I've removed the comment.

2023-01-26 14:12 UTC, PAKovalev approved these changes

2023-01-26 15:16 UTC, dmitry-yudakov commented on packages/app/src/core/utils/router.utils.tsx
> +    return !!matchPath({path: route.path}, currentPath);
Is it clear what replaces now missing `exact`? Or are we supposed to use something like `/a/b/*`? It doesn't feel right to just drop it.

2023-01-26 15:16 UTC, dmitry-yudakov commented on packages/app/src/scenes/App.tsx
> +      <>
Is this extra `<></>` needed?

2023-01-26 15:16 UTC, dmitry-yudakov commented on packages/core/package.json
> +    "react-com": "^1.0.6",
`react-com` seems like a mistake?

2023-01-26 15:16 UTC, dmitry-yudakov commented on packages/core/package.json
> +    "react-dom": "^16.14.0"
`react-dom` should be `^18.2.0`

2023-01-27 09:01 UTC, FIZLIN commented on packages/core/package.json
> +    "react-dom": "^16.14.0"
✅

2023-01-27 09:03 UTC, FIZLIN commented on packages/app/src/scenes/App.tsx
> +      <>
✅

2023-02-17 07:53 UTC, merged