Feature/#1797 music player refactoring
momentum-xyz/ui-client pull request #63
Opened 2022-06-01 09:37 UTC by aminbksi

music player refactored

2022-06-01 13:12 UTC, PAKovalev requested changes

2022-06-01 13:12 UTC, PAKovalev commented on src/scenes/widgets/WidgetContainer.tsx
> +  const handleMusicPlayerClick = () => {
Move to store

2022-06-01 13:12 UTC, PAKovalev commented on src/scenes/widgets/WidgetContainer.tsx
> +      <ReactHowler
It must be part of MusicPlayerWidget

2022-06-01 13:25 UTC, aminbksi commented on src/scenes/widgets/WidgetContainer.tsx
> +  const handleMusicPlayerClick = () => {
I need to call the API to fetch the playlist with worldId

2022-06-01 13:27 UTC, aminbksi commented on src/scenes/widgets/WidgetContainer.tsx
> +      <ReactHowler
ReactHowler on MusicPlayerWidget is Mounted and Unmounted each time the dialog is opened and closed, which is stops and start the player, it should be in the base component which is WidgetContainer here

2022-06-01 14:16 UTC, PAKovalev commented on src/scenes/widgets/WidgetContainer.tsx
> +  const handleMusicPlayerClick = () => {
these is world id in store

2022-06-01 14:17 UTC, Daboo1998 requested changes
Its just part 1 of my review, wait for the rest, you can start working on the ones I submitted in the meantime

2022-06-01 14:17 UTC, Daboo1998 commented on src/component/layout/DashboardSpaceLayout.tsx
> +        handleToggle();
First, make the name descriptive of what it does, maybe something like `togglePlay()` or just `pause()` even (as you wanna pause here if its playing, so make maybe two functions play and pause). Second,  change it to `musicPlayerStore.pause()` instead of just `pause()` son doesn't get mixed up

2022-06-01 14:36 UTC, aminbksi commented on src/core/utils/date.utils.ts
> +export const formatDurationTime = (seconds: number) => {
duration is in seconds, for example if it is 123, the function will do as below:
new Date(floored * 1000).toISOString(); creates "1970-01-01T00:02:03.000Z" and substring from 14th character until length of 5 will be 02:03, and that's the conversion of the duration which is seconds.

2022-06-01 14:42 UTC, aminbksi commented on src/component/layout/DashboardSpaceLayout.tsx
> +  const {handleToggle, playing} = musicPlayerStore;
what do you mean?

2022-06-01 15:21 UTC, aminbksi commented on src/scenes/widgets/WidgetContainer.tsx
> +  } = musicPlayerStore;
done

2022-06-01 15:21 UTC, aminbksi commented on src/scenes/widgets/WidgetContainer.tsx
> +      fetchPlaylist(worldStore.worldId);
done

2022-06-01 15:22 UTC, aminbksi commented on src/scenes/widgets/WidgetContainer.tsx
> +      onClick: handleMusicPlayerClick
done

2022-06-01 15:30 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      handleMuteToggle() {
toggleMute

2022-06-01 15:31 UTC, aminbksi commented on .husky/pre-push
> +command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by delet
all done

2022-06-01 15:34 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      handleMouseUpSeek(e: any) {
seekingEnded, do not pass event

2022-06-01 15:35 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      handleOnPlay() {
startedPlaying

2022-06-01 15:36 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      handleUnmuteButton() {
mute

2022-06-01 15:36 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      handleMuteButton() {
unmute

2022-06-01 15:38 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      handleNext() {
nextSong

2022-06-01 15:40 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      playing: types.optional(types.boolean, true),
isPlaying

2022-06-01 15:42 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      handleOnEnd() {
songEnded

2022-06-01 15:42 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      handlePrevious() {
previousSong

2022-06-01 15:44 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/models/PlayListStore/PlayListStore.ts
> +export {PlayListStore};
add space above

2022-06-01 15:53 UTC, Daboo1998 commented on src/component/layout/DashboardSpaceLayout.tsx
> +  const {handleToggle, playing} = musicPlayerStore;
Don't use `handleToggle()` and `playing`, but `musicPlayerStore.handleToggle()` and `musicPlayerStore.playing`

2022-06-02 07:23 UTC, Daboo1998 commented on src/core/utils/date.utils.ts
> +export const formatDurationTime = (seconds: number) => {
use `Date(floored * 1000).toISOString().match(/(?<=\d\d:)\d\d:\d\d/)[0];` instead of from, length and `Date(floored * 1000).toISOString().substr(from, length)`

2022-06-02 07:25 UTC, Daboo1998 commented on src/core/utils/date.utils.ts
> +export const formatDurationTime = (seconds: number) => {
if you want to show hours then that instead: Date(floored * 1000).toISOString().match(/(\d\d:\d\d:\d\d/)[0];

2022-06-02 08:51 UTC, Daboo1998 requested changes

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/pages/MusicPlayerWidget/MusicPlayerWidget.tsx
> +    if (musicPlayerWidget.isOpen) {
The check doesn't make sense, as the widget is rendered only when `musicPlayerWidget.isOpen === true`, remove it

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/pages/MusicPlayerWidget/components/MusicVolumeController/MusicVolumeController.tsx
> +export interface PropsInterface {}
if there are no props, then I would suggest removing that

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/pages/MusicPlayerWidget/components/PlayerController/PlayerController.tsx
> +export interface PropsInterface {}
No props, so its not needed

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/pages/MusicPlayerWidget/components/SeekBarController/SeekBarController.tsx
> +export interface PropsInterface {}
No props -> remove

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/pages/MusicPlayerWidget/components/UnityVolumeController/UnityVolumeController.tsx
> +  const UnityMuted = useUnityStore((state) => state.muted);
use unityStore for that

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/pages/MusicPlayerWidget/components/UnityVolumeController/UnityVolumeController.tsx
> +    unityStore.muteUnity(UnityMuted);
When you do what I said in previous comment, then here just do `unityStore.mute()` (without params, and 'Unity' word in `muteUnity` isn't needed here, as we know its unity by store name)

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/pages/MusicPlayerWidget/components/UnityVolumeController/UnityVolumeController.tsx
> +    unityStore.volumeChange(slider, UnityMuted);
Same, `unityStore.changeVolume(slider)` (without UnityMuted parameter)

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      next: types.optional(types.boolean, true),
If it as you said to tell that next song should be playing, then call it accordingly i.e. `nextSongShouldBePlaying`.

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/MusicPlayerStore.ts
> +      start: types.optional(types.boolean, false),
If it as you said to tell that when clicking previous track it should start again or got to previous track, then call it accordingly i.e. `previousStartsAgain`.

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/models/PlayListStore/PlayListStore.ts
> +      self.currentTrackHash = cast(
no need to cast

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/models/PlayListStore/PlayListStore.ts
> +        appVariables.RENDER_SERVICE_URL + `/track/${self.tracks[self.currentSrcIndex].trackHash}`
put `appVariables.RENDER_SERVICE_URL` inside the template string

2022-06-02 08:51 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/models/PlayListStore/PlayListStore.ts
> +      const response: PlaylistResponse[] = yield self.request.send(
`PlaylistResponse` should extend from `PlaylistItem[]` or `Track[]` of some sort. Return type of response should be `PlaylistResponse` not `PlaylistResponse[]`

2022-06-02 08:51 UTC, Daboo1998 commented on src/stores/MainStore/models/UnityStore/UnityStore.ts
> +    volume: types.optional(types.number, 0.0)
add muted parameter here and use that instead of `useUnityStore((state) => state.muted);`

2022-06-02 08:51 UTC, Daboo1998 commented on src/ui-kit/organisms/PanelLayout/PanelLayout.styled.ts
> +export const HeaderItem = styled.div<{titleWidth: string}>`
actually instead of prop use style={{width: titleWidth}} (I did as you before, but actually this way is better)

2022-06-02 08:51 UTC, Daboo1998 commented on src/ui-kit/organisms/PanelLayout/PanelLayout.tsx
> +          <styled.HeaderItem className={cn(headerItem)} titleWidth={titleWidth}>
As I said before `<styled.HeaderItem className={cn(headerItem)} style={{width: titleWidth}}>`

2022-06-02 13:42 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/models/MusicPlayer/MusicPlayer.ts
> +    seekingEnded(e: any) {
pass value here instead of event. call the parameter seekValue

2022-06-02 13:43 UTC, Daboo1998 commented on src/scenes/widgets/stores/MusicPlayerStore/models/MusicPlayer/MusicPlayer.ts
> +    seekingChange(e: any) {
same as above

2022-06-02 15:09 UTC, Daboo1998 approved these changes

2022-06-02 16:20 UTC, merged