Odyssey Portal
momentum-xyz/ui-client pull request #636
Opened 2023-02-07 11:36 UTC by FIZLIN

DEV-67

2023-02-07 14:16 UTC, PAKovalev requested changes

2023-02-07 14:16 UTC, PAKovalev commented on packages/app/src/scenes/widgets/stores/OdysseyPortalStore/OdysseyPortalStore.ts
> +const OdysseyPortalStore = types.compose(
It is a duplication of `OdysseyBioStore` store. We don't need to have and support two the same models.

2023-02-07 14:16 UTC, PAKovalev commented on packages/app/src/scenes/widgets/pages/OdysseyPortalWidget/OdysseyPortalWidget.tsx
> +const OdysseyPortalWidget: FC<PropsInterface> = () => {
I think we can reuse a `OdysseyInfoWidget` widget instead of creating a new one.

2023-02-07 14:16 UTC, PAKovalev commented on packages/app/src/scenes/widgets/Widgets.tsx
> +      {widgetsStore.odysseyPortalStore.dialog.isOpen && <OdysseyPortalWidget />}
Don't need to have this.

2023-02-07 14:16 UTC, PAKovalev commented on packages/app/src/scenes/widgets/Widgets.tsx
> +  useUnityEvent('ClickObjectEvent', (spaceId: string, label: string) => {
We have the hook under a `UnityPage`. Just extended that handler.

`const nft = nftStore.getNftByUuid(SOME_ID);
  if (nft) {
      widgetsStore.odysseyInfoStore.open(nft);
  }`

2023-02-07 16:20 UTC, FIZLIN commented on packages/app/src/scenes/widgets/stores/OdysseyPortalStore/OdysseyPortalStore.ts
> +const OdysseyPortalStore = types.compose(
✅

2023-02-07 16:20 UTC, FIZLIN commented on packages/app/src/scenes/widgets/pages/OdysseyPortalWidget/OdysseyPortalWidget.tsx
> +const OdysseyPortalWidget: FC<PropsInterface> = () => {
✅

2023-02-07 16:20 UTC, FIZLIN commented on packages/app/src/scenes/widgets/Widgets.tsx
> +      {widgetsStore.odysseyPortalStore.dialog.isOpen && <OdysseyPortalWidget />}
✅

2023-02-07 16:20 UTC, FIZLIN commented on packages/app/src/scenes/widgets/Widgets.tsx
> +  useUnityEvent('ClickObjectEvent', (spaceId: string, label: string) => {
✅

2023-02-08 07:21 UTC, PAKovalev requested changes

2023-02-08 07:21 UTC, PAKovalev commented on packages/app/src/scenes/widgets/stores/OdysseyBioStore/OdysseyBioStore.ts
> +          self.onOdysseyWorld = openingOdysseyWorld;
`onOdysseyWorld` what does it mean? Looks like some handler. :)

2023-02-08 07:56 UTC, FIZLIN commented on packages/app/src/scenes/widgets/stores/OdysseyBioStore/OdysseyBioStore.ts
> +          self.onOdysseyWorld = openingOdysseyWorld;
Fair point.

2023-02-08 07:58 UTC, FIZLIN commented on packages/app/src/scenes/widgets/stores/OdysseyBioStore/OdysseyBioStore.ts
> +          self.onOdysseyWorld = openingOdysseyWorld;
✅

2023-02-08 08:17 UTC, PAKovalev approved these changes

2023-02-08 09:20 UTC, dmitry-yudakov approved these changes

2023-02-08 13:21 UTC, dmitry-yudakov approved these changes
It's ok in general and could be merged, though one thing may be improved.

2023-02-08 13:21 UTC, dmitry-yudakov commented on packages/app/src/scenes/widgets/stores/OdysseyBioStore/OdysseyBioStore.ts
> +      isOnOdysseyWorld: false,
Maybe it's better be a "view" function rather than model field? Checking that current nft is matching Odyssey id. ODYSSEY_WORLD_ID could be put to appVariables or maybe there's a better place for these... @PAKovalev

2023-02-08 14:08 UTC, FIZLIN commented on packages/app/src/scenes/widgets/stores/OdysseyBioStore/OdysseyBioStore.ts
> +      isOnOdysseyWorld: false,
I exported the variable to the app variables and move the boolean to a view.

2023-02-09 09:13 UTC, merged