Feat/storybook/hexagon
momentum-xyz/ui-client pull request #656
Opened 2023-02-22 09:32 UTC by FIZLIN

2023-02-27 08:01 UTC, PAKovalev requested changes

2023-02-27 08:01 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +  isBlank?: boolean;
Make variants instead of isBlank, isBlueBorder, isBordered props. Like `HexagonSizeType`

2023-02-27 08:01 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +  className?: string;
Don't use classname. Classname comes from styled-components internally. Otherwise - you can not overrite styles using styled-components approach.

2023-03-08 12:01 UTC, FIZLIN commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +        <styled.Sparkle
I wonder if we should move this to a separate component or icon?

2023-03-08 12:01 UTC, FIZLIN commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.styled.ts
> +};
I made these like so, because they are used in both the `Wrapper` and `Hexagon` styles.

2023-03-13 07:22 UTC, PAKovalev requested changes

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.stories.tsx
> +      <Hexagon {...(Primary.args as HexagonPropsInterface)}>
Create a template instead if decorators. It should be:

`const Template: Story<HexagonPropsInterface> = (args) => 
<Hexagon {...args}>
  <img />
</Hexagon>;`

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.stories.tsx
> +          src="https://global-uploads.webflow.com/600af1368b0b4075be07c984/632ad6edc4c62f89d965aca6_Jetsons-60th-Anniversary.jpg"
Create a const for image:  
`const IMAGE_SRC = 'https://picsum.photos/300'`

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.stories.tsx
> +      <div style={{display: 'flex', alignItems: 'center'}}>
`<div className="storybook-grid">`

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.styled.ts
> +};
I guess if we define as normal css constants under wrapper they will be available under Hexagon. Isn't it? Could you check pls.

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +type HexagonType = 'primary' | 'secondary-large' | 'secondary' | 'secondary-small' | 'blank';
I guess, it will be better to have:
`type HexagonType = 'primary' | 'secondary' | 'third' | 'fourth' | 'blank';`

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +    noBorder,
Can it be a different type? I'd suggest to avoid big list of props.

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +    skipOuterBorder,
Can it be a different type? I'd suggest to avoid big list of props.

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +  const size: HexagonSizeType = ['primary', 'secondary-large'].includes(type)
It looks like non-simple logic. Can we avoid it? Don't worry about mixing props. We have to use what we need.

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +  const isOuterBorder = !skipOuterBorder && type === 'primary';
Are you sure we really need this?

2023-03-13 07:22 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +        <styled.Sparkle
Yeah, lets create an svg image for this.

2023-03-13 14:46 UTC, FIZLIN commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +    noBorder,
✅

2023-03-13 14:46 UTC, FIZLIN commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.stories.tsx
> +          src="https://global-uploads.webflow.com/600af1368b0b4075be07c984/632ad6edc4c62f89d965aca6_Jetsons-60th-Anniversary.jpg"
✅

2023-03-13 14:46 UTC, FIZLIN commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.stories.tsx
> +      <div style={{display: 'flex', alignItems: 'center'}}>
✅

2023-03-13 14:46 UTC, FIZLIN commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +    skipOuterBorder,
We discussed to leave this on a private call.

2023-03-13 14:57 UTC, FIZLIN commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.stories.tsx
> +      <Hexagon {...(Primary.args as HexagonPropsInterface)}>
✅

2023-03-13 14:57 UTC, FIZLIN commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.styled.ts
> +};
Yep, that works ✅

2023-03-14 07:08 UTC, PAKovalev approved these changes

2023-03-14 07:08 UTC, PAKovalev commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +import Sparkle from '../../assets/icons/sparkle.svg';
move this file to `static/images`. Assets folder has icons for a sprite only.

2023-03-14 09:08 UTC, FIZLIN commented on packages/ui-kit-storybook/src/atoms/Hexagon/Hexagon.tsx
> +import Sparkle from '../../assets/icons/sparkle.svg';
✅

2023-03-14 09:09 UTC, merged