feat(storybook): Side Menu
momentum-xyz/ui-client pull request #688
Opened 2023-03-20 09:11 UTC by FIZLIN

2023-03-20 10:26 UTC, PAKovalev requested changes

2023-03-20 10:26 UTC, PAKovalev commented on packages/ui-kit-storybook/src/molecules/SideMenu/SideMenu.stories.tsx
> +const Template: Story<SideMenuPropsInterface> = (args) => <SideMenu {...args} />;
Make `useState` for storing active id.

2023-03-20 10:26 UTC, PAKovalev commented on packages/ui-kit-storybook/src/molecules/SideMenu/SideMenu.tsx
> +  const [activeMenuItemIdx, setActiveMenuItemIdx] = useState(activeIdx || 0);
Don't need this. Active id should come from props.

2023-03-20 10:26 UTC, PAKovalev commented on packages/ui-kit-storybook/src/molecules/SideMenu/SideMenu.tsx
> +                {sideMenuItem.pinNumber < 10 ? '0' : ''}
Make a const for `10` above.

2023-03-20 10:26 UTC, PAKovalev commented on packages/ui-kit-storybook/src/molecules/SideMenu/SideMenu.tsx
> +  const onClick = (idx: number) => {
Don't need this also.

2023-03-21 07:51 UTC, FIZLIN commented on packages/ui-kit-storybook/src/molecules/SideMenu/SideMenu.tsx
> +  const onClick = (idx: number) => {
✅

2023-03-21 07:51 UTC, FIZLIN commented on packages/ui-kit-storybook/src/molecules/SideMenu/SideMenu.tsx
> +                {sideMenuItem.pinNumber < 10 ? '0' : ''}
✅

2023-03-21 07:51 UTC, FIZLIN commented on packages/ui-kit-storybook/src/molecules/SideMenu/SideMenu.tsx
> +  const [activeMenuItemIdx, setActiveMenuItemIdx] = useState(activeIdx || 0);
✅

2023-03-21 07:51 UTC, FIZLIN commented on packages/ui-kit-storybook/src/molecules/SideMenu/SideMenu.stories.tsx
> +const Template: Story<SideMenuPropsInterface> = (args) => <SideMenu {...args} />;
✅

2023-03-21 08:13 UTC, PAKovalev approved these changes

2023-03-21 08:13 UTC, merged