Refactored EventItemModel into separate model and store
momentum-xyz/ui-client pull request #92
Opened 2022-06-20 14:33 UTC by Daboo1998

2022-06-21 06:38 UTC, aminbksi commented on src/ui-kit/organisms/EventItem/EventItem.tsx
> +
the problem with updating is here, on init either the fetchMagicLink or fetchAttendees has null/undefined field(s) not handled, try to init somewhere else or handle the null/undefined fields

2022-06-22 11:03 UTC, aminbksi commented on src/scenes/widgets/pages/AttendeesWidget/AttendeesWidget.tsx
> +      title="Gathering Name"
translation missing or maybe for title the event title should be here?

2022-06-22 11:05 UTC, aminbksi commented on src/scenes/widgets/pages/AttendeesWidget/AttendeesWidget.tsx
> +        title="Gathering Name"
same here

2022-06-22 11:07 UTC, PAKovalev requested changes

2022-06-22 11:07 UTC, PAKovalev commented on src/scenes/widgets/pages/AttendeesWidget/AttendeesWidget.styled.ts
> +import {ProfileWidget} from '../ProfileWidget';
Bad idea. Why do we have this relation?

2022-06-22 11:07 UTC, PAKovalev commented on src/scenes/widgets/pages/AttendeesWidget/AttendeesWidget.tsx
> +        subtitle={`Attendee List / ${t('counts.attendees', {
i18n

2022-06-22 11:37 UTC, Daboo1998 commented on src/scenes/widgets/pages/AttendeesWidget/AttendeesWidget.styled.ts
> +import {ProfileWidget} from '../ProfileWidget';
I need to style Profile Widget to show next to the AttendeesWidget
I can change import

2022-06-22 12:12 UTC, aminbksi approved these changes

2022-06-22 12:22 UTC, PAKovalev approved these changes

2022-06-22 12:33 UTC, merged