Newsfeed Infinite Loader
momentum-xyz/ui-client pull request #940
Opened 2023-06-01 08:33 UTC by FIZLIN

2023-06-06 12:31 UTC, PAKovalev requested changes

2023-06-06 12:31 UTC, PAKovalev commented on packages/app/src/scenes/widgets/pages/NewsfeedWidget/NewsfeedWidget.tsx
> +            height={1000}
Use `react-virtualized-auto-sizer` for getting size. It is AutoSizer component.
See here https://github.com/bvaughn/react-window

2023-06-06 12:31 UTC, PAKovalev commented on packages/ui-kit/src/organisms/NewsfeedEntry/NewsfeedEntry.tsx
> +  const entryDate = new Date(entry.created_at);
Move this to the `app/src/core/utils`

2023-06-06 12:31 UTC, PAKovalev commented on packages/app/src/scenes/widgets/pages/NewsfeedWidget/NewsfeedWidget.tsx
> +            estimatedItemSize={116}
Not all items will have the same size. Can we set 'auto' or calculate somehow? lets test it with different sizes of items.

2023-06-07 07:32 UTC, FIZLIN commented on packages/ui-kit/src/organisms/NewsfeedEntry/NewsfeedEntry.tsx
> +  const entryDate = new Date(entry.created_at);
✅

2023-06-07 07:33 UTC, FIZLIN commented on packages/app/src/scenes/widgets/pages/NewsfeedWidget/NewsfeedWidget.tsx
> +            estimatedItemSize={116}
I've added a rudimentary calculation in the `itemSize`. That number is only for the initial calculations.

2023-06-08 12:31 UTC, merged